### ISSUE TITLE
dpctl does not detect gpu devices after latest dppy/label/dev push ?

### ISSUE THREAD

**Issue by fcharras** [IntelPython/dpctl#1006]
I think something broke regarding gpu detection after [push from 2022-12-03](https://anaconda.org/dppy/repo?type=conda&label=dev)

Here are the installation instructions I'm using: (tested both in fresh ubuntu 2004 and 2204 docker containers)

```
apt-get update --quiet
apt-get install -y wget
apt-get install -y intel-opencl-icd
# or
# apt-get install -y python3
# wget https://raw.githubusercontent.com/intel/llvm/sycl/devops/scripts/get_release.py
# wget https://raw.githubusercontent.com/intel/llvm/sycl/devops/scripts/install_drivers.sh
# compute_runtime_tag=latest igc_tag=latest cm_tag=latest tbb_tag=latest fpgaemu_tag=latest cpu_tag=latest bash install_drivers.sh --all
cd
wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
bash Mambaforge-Linux-x86_64.sh
source .bashrc
mamba create -n my-dpex-env numba-dpex dpcpp_linux-64 -c conda-forge -c dppy/label/dev -c intel
mamba env config vars set OCL_ICD_FILENAMES_RESET=1 OCL_ICD_FILENAMES=libintelocl.so -n my-dpex-env
mamba activate my-dpex-env
python -c "import dpctl; print(dpctl.get_devices())"
```

I'm almost certain this last python command would print both cpu and gpu devices when tested on `2022-12-02` but from today on I tried several variations of those commands and can't get any gpu device to be detected. On the other hand it seems that setting `OCL_ICD_FILENAMES_RESET=1 OCL_ICD_FILENAMES=libintelocl.so` is not required anymore for `cpu` to be detected.

I think @oleksandr-pavlyk was trying to bundle the drivers in the conda installation tree maybe this is related ? my guess would be that now `dpctl` is correctly using `libintelocl.so` in the conda prefix, but it stopped using `ls /etc/OpenCL/vendors/intel.icd` (or some other thing it was using before) to get to `libigdrcl.so` ?

**Comment by oleksandr-pavlyk** [comment]
@fcharras Could you please specify the output of `python -c "import dpctl; dpctl.lsplatform(verbosity=2)"`? 

The changes to bundling of drivers in conda installation tree has been been published yet. Something else is going on here.

**Comment by fcharras** [comment]
```
Platform  0 ::
    Name        Intel(R) OpenCL
    Version     OpenCL 3.0 LINUX
    Vendor      Intel(R) Corporation
    Backend     opencl
    Num Devices 1
      # 0
        Name                11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
        Version             2022.14.7.0.30_160000
        Filter string       opencl:cpu:0
Platform  1 ::
    Name        SYCL host platform
    Version     1.2
    Vendor      unknown
    Backend     unknown
    Num Devices 1
      # 0
        Name                SYCL host device
        Version             1.2
        Filter string       host:host:0
```

**Comment by oleksandr-pavlyk** [comment]
@fcharras It may be that DPC++ RT is encountering difficulties with drivers. This can be diagnosed with setting `SYCL_PI_TRACE=1`, e.g. use `SYCL_PI_TRACE=1 python -c "import dpctl; dpctl.lsplatform()"`.

At the top of the output I am seeing 

```
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_opencl.so
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_level_zero.so
```

Also it would be helpful to ensure that no inconsistency exists in your environment. Can you please include the output of `conda list --explicit`, at least portions related to DPC++ runtimes and to `dpctl`.

**Comment by fcharras** [comment]
```
(my-dpex-env) root@5d0bb7588cb5:~# SYCL_PI_TRACE=1 python -c "import dpctl; dpctl.lsplatform()"
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_opencl.so
Intel(R) OpenCL OpenCL 3.0 LINUX
SYCL host platform 1.2
```

**Comment by oleksandr-pavlyk** [comment]
@fcharras Further diagnostics depends on whether you use conda-forge's OpenCL loader, or the one obtained from Intel. 

The difference is that conda-forge's will only use `$PREFIX/etc/OpenCL/vendors`, while Intel's will use `/etc/OpenCL/vendors`. Since GPU drivers are not presently available packages in conda environment, please make sure you use `intel-opencl-rt` from `intel` channel, not from `conda-forge` channel.

**Comment by fcharras** [comment]
Using `mamba create -n my-dpex-env numba-dpex dpcpp_linux-64 -c dppy/label/dev -c intel` rather than `mamba create -n my-dpex-env numba-dpex dpcpp_linux-64 -c conda-forge -c dppy/label/dev -c intel` (so install everything from intel channel except for dppy/label/dev packages) gives the same outcome.

**Comment by fcharras** [comment]
I'm getting progress on the issue, I have it in a working state again with a more complicated procedure for installing gpu drivers and using

`mamba create -n my-dpex-env numba-dpex "intel::dpcpp_linux-64" -c dppy/label/dev -c conda-forge -c intel`

I'll update the guide when I understand more which driver package is necessary.

**Comment by fcharras** [comment]
For the GPU, the driver issue comes down to what version of `intel-icd-opencl` is installed.

If using ubuntu 2204 repositories we have [intel-opencl-icd (22.14.22890-1)](https://packages.ubuntu.com/jammy/intel-opencl-icd), gpu is not detected.

Using [latest release](https://github.com/intel/compute-runtime/releases/tag/22.43.24595.30):
```
apt-get remove  intel-opencl-icd
wget https://github.com/intel/compute-runtime/releases/download/22.43.24595.30/intel-opencl-icd_22.43.24595.30_amd64.deb 
dpkg -i intel-opencl-icd_22.43.24595.30_amd64.deb 
```

it works.

**Comment by fcharras** [comment]
Digging deeper, it also works when installing the same version than in jammy repositories, but [from the github repository](https://github.com/intel/compute-runtime/releases/tag/22.14.22890).

Upon inspection, the files contain the same files. But the hashes are different:

- from github:
```
b0a947fc745fabdc6fce6e2fc7afaddc  usr/bin/ocloc
f21f6c827d91b71d554237a201e4d944  usr/include/ocloc_api.h
9da139f061468f77082753f7ab2e9aed  usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
93355007cf89208b64541f0ab93bd98b  usr/lib/x86_64-linux-gnu/libocloc.so
c6750f20b956645e48df4c5fa76700a8  usr/share/doc/intel-opencl-icd/changelog.gz
c80a9da2bc90e48c74a0ccf6e7112456  usr/share/doc/intel-opencl-icd/copyright
```
- from jammy repositories:
```
608c6f47383c60c768e96e96769e73a5  usr/bin/ocloc
f21f6c827d91b71d554237a201e4d944  usr/include/ocloc_api.h
853931b595b11e4cb3fdac3d2c0e1071  usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
eca15d887439a9a061071da366746c85  usr/lib/x86_64-linux-gnu/libocloc.so
a384878d401c06b1bbc82943da737160  usr/share/doc/intel-opencl-icd/changelog.Debian.gz
1318fcd717c589e69821ce57e74d44c7  usr/share/doc/intel-opencl-icd/copyright
```

So apparently those two are not built the same way and it's causing compatibility issues ? @oleksandr-pavlyk do you think this could be an issue on the dpctl/sycl or in the ubuntu distribution ? if ubuntu i'll forward the bug report.

**Comment by oleksandr-pavlyk** [comment]
Based on your last comment, this has to do with Intel Compute Runtime component (intel-opencl-icd) which implements OpenCL driver for Intel(R) UHD Graphics. Also since changing changing the libraries without changing DPC++ installation and `dpctl` package fixed the issue, the involvement of DPC++ runtime and `dpctl` libraries is unlikely. 

There must be an issue with those particular libraries. I'd start with reporting to Ubuntu.

**Comment by fcharras** [comment]
Maybe this issue could be closed and a new one opened with the actual issue. I think it should also be track as a `dpctl` issue, many users trying to install this stack are going to run into the same troubles, given that the `apt-get` based install is actually listed as recommended https://github.com/intel/compute-runtime#via-system-package-manager. 

I must believe my initial report of behavior change with releases from 03/12 is wrong, and I got confused in combinations of instructions that are possible (regarding driver installation and channel parameters).
