### ISSUE TITLE
Compatibility with `libsycl.so.6`

### ISSUE THREAD

**Issue by fcharras** [IntelPython/dpctl#1022]
It seems the conda package on channel `dppy/label/dev` is compatible with `libsycl.so.5` but not `libsycl.so.6`. But `intel` just released `2023.0.0` versions of all the dependencies on `conda` and `pypi` and it ships `libsycl.so.6` thus breaking the `dpctl` conda distribution:

```
    from ._sycl_device import SyclDevice, SyclDeviceCreationError
ImportError: libsycl.so.5: cannot open shared object file: No such file or directory

```

Would it be possible to update the build to work with `libsycl.so.6` ?

**Comment by fcharras** [comment]
Maybe `dpnp` and `numba_dpex` in the same channel will be affected too ?

**Comment by fcharras** [comment]
In the meantime the dpcpp runtime can be pinned in conda, e.g with

```
export CONDA_DPEX_ENV_NAME=my-dpex-env
conda creaIn the meantime the dpcpp runtime can be pinned in conda, e.g with

```
export CONDA_DPEX_ENV_NAME=my-dpex-env
conda create --yes --name $CONDA_DPEX_ENV_NAME \
             --channel dppy/label/dev \
             --channel conda-forge \
             --channel intel \
             `# TODO: remove <2023.0.0 pin after dppy/label/dev is updated` \
             numba-dpex "intel::dpcpp_linux-64<2023.0.0"
```

**Comment by oleksandr-pavlyk** [comment]
dpctl 0.14.1dev1 built with DPC++ 2023.0.0 has been uploaded to dppy/label/dev. It would be compatible with `libsycl.so.6`

**Comment by fcharras** [comment]
Thank you for the bumps.

I'm getting this new error though:

```
AttributeError: 'dpctl._sycl_device.SyclDevice' object has no attribute 'sub_group_sizes'
```

(using the custom build form this [Dockerfile](https://github.com/soda-inria/sklearn-numba-dpex/blob/main/docker/Dockerfile)

When on CPU (`SYCL_DEVICE_FILTER=cpu`) I'm also having `dpctl._sycl_queue.SyclKernelSubmitError: Kernel submission to Sycl queue failed.` errors. How can I debug such errors ? (reported in https://github.com/IntelPython/dpctl/issues/1023)
