### ISSUE TITLE
get_current_queue and other functions should be exposed as cpdef functions

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#112]
dpctl functions `get_current_queue`, `get_current_device`, `get_current_backend` are not exposed as C functions. Other Cython modules that want to use dpctl cannot do a cimport to access these functions.

We should redefine these functions as cpdef and expose them via _sycl_core.pxd.

**Comment by oleksandr-pavlyk** [comment]
https://github.com/IntelPython/dpctl/pull/125 exports `get_current_queue`.
