### ISSUE TITLE
All flags are read-only?

### ISSUE THREAD

**Issue by DrTodd13** [IntelPython/dpctl#1138]
Some of the flags in NumPy are modifiable, e.g., "writeable."  It doesn't seem like dpctl.tensor._flags.Flags allows writeable to be changed.

**Comment by oleksandr-pavlyk** [comment]
@DrTodd13 I just implemented the feature. Use `x.flags.writable = False` to make the array read-only.

**Comment by DrTodd13** [comment]
@oleksandr-pavlyk Thanks!
