### ISSUE TITLE
Last version on PYPI is 0.11.3

### ISSUE THREAD

**Issue by yurivict** [IntelPython/dpctl#1152]

**Comment by oleksandr-pavlyk** [comment]
@yurivict Wheels for newer version is available from anaconda, see https://anaconda.org/intel/dpctl

```
pip install -i https://pypi.anaconda.org/intel/simple dpctl
```

**Comment by yurivict** [comment]
But https://pypi.org is also supposed to have the last tarball.

**Comment by oleksandr-pavlyk** [comment]
The dpctl=0.14.5 has been published on PyPI: https://pypi.org/project/dpctl/
