### ISSUE TITLE
dpctl crashes when there is no opencl device

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/dpctl#119]
By importing dpctl and calling dpctl.is_in_device_context() this error can be triggered.

terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  No device of requested type available. Please check https://software.intel.com/en-us/articles/intel-oneapi-dpcpp-compiler-system-requirements-beta -1 (CL_DEVICE_NOT_FOUND)
Fatal Python error: Aborted

**Comment by diptorupd** [comment]
Fixed in #116
