### ISSUE TITLE
Compare USM with RMM

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#126]
Rapids Memory Manager (RMM):
https://github.com/rapidsai/rmm#using-rmm-in-python-code
http://numba.pydata.org/numba-doc/latest/cuda/external-memory.html#setting-the-emm-plugin

Related to #34

**Comment by oleksandr-pavlyk** [comment]
RMM implements `DeviceBuffer` which is Cython native class wrapping around something similar to `std::vector<unsigned char, custom_cuda_allocator (calls resource manager)>` which is called `device_buffer`.

`DeviceBuffer` stores a unique pointer to an instance of this class. `DeviceBuffer` implements `__cuda_array_interface__`. Direct constructors always allocate new memory and copy provided inputs into the newly allocated array. 

Zero-copy construction is possible from a `unique_ptr<device_ buffer>`, with the ownership being moved to the Cython extension instance. 

DeviceBuffer provides `__reduce__` method to support pickling (which works by copying content of the device buffer to host) and provides the following set of routines, among others:
   - `copy_to_host(host_buf_obj)` to copy content of the underlying device_buffer to a host buffer
   - `copy_from_host(host_buf_obf)` to copy content of the host buffer into memory of underlying device_buffer
   - `copy_from_device(cuda_ary_obj)` to copy device memory underyling `cuda_ary_obj` Python object implementing `__cuda_array_interface__` to the memory underlying `DeviceBuffer` instance. 

RMM's methods are declared `nogil`.

**Comment by diptorupd** [comment]
I have documented the current discussion in our docs under `dpctl.memory`. Closing this issue.

**Comment by PokhodenkoSA** [comment]
Related: https://github.com/IntelPython/dpctl/pull/140
