### ISSUE TITLE
Link to the CUDA array interface on the "Zero copy data exchange using SYCL USM" Wiki page is outdated

### ISSUE THREAD

**Issue by Vika-F** [IntelPython/dpctl#1286]
Please update the link to the `__cuda_array_interface__` on the Wiki page.
Please see the updated link here: https://github.com/Vika-F/dpctl/blob/dev/vsfedoto/dpctl_wiki_link_fix/Zero-copy-data-exchange-using-SYCL-USM.md

**Comment by oleksandr-pavlyk** [comment]
Thank you @Vika-F . I have updated the link in the [project's wiki page](https://github.com/IntelPython/dpctl/wiki/Zero-copy-data-exchange-using-SYCL-USM).

**Comment by oleksandr-pavlyk** [comment]
Please verify and close.

**Comment by oleksandr-pavlyk** [comment]
Closing.
