### ISSUE TITLE
Standardize C/C++ code style among projects

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#136]
Configuration file `.clang-format` should be discussed.
There are projects like dpNP and daal4py which also use clang-format and have `.clang-format`. 
It is better to have similar style among projects.

**Comment by oleksandr-pavlyk** [comment]
Choices made in `_clang-format` used in daal4py was necessitated by shortcomings of daal4py's C++ header parser, so I am not sure it needs to be replicated across projects.

**Comment by Alexander-Makaryev** [comment]
> Choices made in `_clang-format` used in daal4py was necessitated by shortcomings of daal4py's C++ header parser, so I am not sure it needs to be replicated across projects.

It is a copy of config from original DAAL with single change ColumnLimit field. So it is not a synthetic example, it is used in huge and serious c++ project.
https://github.com/oneapi-src/oneDAL/blob/master/cpp/daal/.clang-format

**Comment by diptorupd** [comment]
It might be hard to share coding style across projects, especially if there is no sharing of code. E.g. oneDAL's `ColumnLimit=150` is not acceptable to me. I will go with LLVM's standard https://llvm.org/docs/CodingStandards.html with perhaps some minor modifications.

**Comment by diptorupd** [comment]
We now have a `clang-format` for the dpctl C API. Closing this ticket. Please reopen if we really want to discuss an IntelPython C coding style.
