### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#137]
- [ ] #2 - request for SYCL examples

**Comment by PokhodenkoSA** [comment]
@diptorupd could you please add examples you want to see in gold release?

**Comment by oleksandr-pavlyk** [comment]
I have added some examples in branch examples-added. Still WIP though

**Comment by PokhodenkoSA** [comment]
> I have added some examples in branch examples-added. Still WIP though

I would like to review when you will create a PR.
I think in this ticket we could track topics we want to cover with examples. 
@oleksandr-pavlyk please fill free to modify lists in the header of this ticket.

**Comment by diptorupd** [comment]
Closing as we now have initial set of examples that got added by #197. More examples are needed, but we should open specific tickets for them rather than keep this catch-all issue open.
