### ISSUE TITLE
output array with a data type higher in hierarchy

### ISSUE THREAD

**Issue by vtavana** [IntelPython/dpctl#1379]
In `dpctl`, if the type of output array is higher in hierarchy compared to expected data type, a `TypeError` is returned while `numpy` works fine in this situation. For instance, in `numpy`, we can have
```
>>> import numpy
>>> x_np = numpy.array([2,4],dtype='f4')
>>> y_np = numpy.empty(2,dtype='f8')
>>> numpy.tan(x_np,out=y_np)
array([-2.18503976,  1.1578213 ])
```
while `dpctl` raises an error (should be run on a device that support `f8`)
```
 >>> import dpctl,dpctl.tensor as dpt
 >>> x_dpt = dpt.asarray([2,4],dtype='f4')
 >>> y_dpt = dpt.empty(2,dtype='f8')
 >>> dpt.tan(x_dpt,out=y_dpt)
 
 File /localdisk/work/vtavanas/repos/dpctl/dpctl/tensor/_elementwise_common.py:101, in UnaryElementwiseFunc.__call__(self, x, out, order)
     95     raise ValueError(
     96         "The shape of input and output arrays are inconsistent. "
     97         f"Expected output shape is {x.shape}, got {out.shape}"
     98     )
    100 if res_dt != out.dtype:
--> 101     raise TypeError(
    102         f"Output array of type {res_dt} is needed,"
    103         f" got {out.dtype}"
    104     )
    106 if (
    107     buf_dt is None
    108     and ti._array_overlap(x, out)
   (...)
    112     # Note if `buf_dt` is not None, a temporary copy of `x` will be
    113     # created, so the array overlap check isn't needed.
    114     out = dpt.empty_like(out)

TypeError: Output array of type float32 is needed, got float64
```

**Comment by oleksandr-pavlyk** [comment]
The NumPy universal functions support `dtype` parameter, that allows one to create output array of the required type. I do not know whether it works by upcasting the input arrays, or upcasting the results (the former would make more sense). 

`dpctl` does not support `dtype` parameter, and hence can only support `out` arrays of the same dtype as would have been generated automatically. 

If the user wants a different output type, the user should be advise to cast the input as necessary.

**Comment by oleksandr-pavlyk** [comment]
I should add that the information about what type to cast the input to can be gleaned from `dpt.tan.types` attribute.
