### ISSUE TITLE
Use setup.py for building C++ backend

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#145]
For Python users it is more convenient to work with package via setup.py file. It is the standard way to build and develop package.
So building package `python setup.py install` or developing package `python setup.py develop` should also build C++ code for backend.
Example: https://github.com/numba/llvmlite
https://github.com/numba/llvmlite/blob/1f25fa723e419e77c325a135e10acfb9b6112e8f/setup.py#L45 - from setup.py call Python script for build CMake
https://github.com/numba/llvmlite/blob/master/ffi/build.py - Python script for build CMake

User can build package via `python setup.py install`.
Also conda scripts become simpler.
Also developers will not require to create custom scripts for building parts of the project. All parts could be built via setup.py.

**Comment by diptorupd** [comment]
Thanks @1e-to. I tried it and it is really nice :+1:
