### ISSUE TITLE
Add optional CMake rules to build tests, examples, documentation

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#156]
Clean up the CMake a bit to build the tests, docs, examples as needed
- [x] tests
- [ ] examples
- [x] docs

**Comment by diptorupd** [comment]
Docs and tests already have CMake support.

**Comment by PokhodenkoSA** [comment]
@diptorupd Do we support running examples via CMake now?

**Comment by diptorupd** [comment]
Since the examples are purely Python/Cython CMake is not needed. In future, if we write C API examples, we will create CMake builders for those examples.

I am closing the ticket.
