### ISSUE TITLE
Support for Gen13 Raptor-lake on arch-based distributions

### ISSUE THREAD

**Issue by fcharras** [IntelPython/dpctl#1600]
After I upgrade to more recent hardware `dpctl` doesn't detect the gpu:

```
root@4d14ca598997:~# python -c "import dpctl; print(dpctl.get_devices())"
[<dpctl.SyclDevice [backend_type.opencl, device_type.accelerator,  Intel(R) FPGA Emulation Device] at 0x7db1c1bb8ff0>, <dpctl.SyclDevice [backend_type.opencl, device_type.cpu,  13th Gen Intel(R) Core(TM) i5-1335U] at 0x7db1c1bb8ef0>]
```

Here are my hardware specs given by `lshw`:

```
# lshw -C display
  *-display                 
       description: VGA compatible controller
       product: Raptor Lake-P [Iris Xe Graphics]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 04
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 mode=1920x1200 resolution=1920,1200 visual=truecolor xres=1920 yres=1200
       resources: iomemory:600-5ff iomemory:400-3ff irq:201 memory:603c000000-603cffffff memory:4000000000-400fffffff ioport:2000(size=64) memory:c0000-dffff memory:4010000000-4016ffffff memory:4020000000-40ffffffff
# lshw -class CPU
  *-cpu                     
       description: CPU
       product: 13th Gen Intel(R) Core(TM) i5-1335U
       vendor: Intel Corp.
       physical id: 1a
       bus info: cpu@0
       version: 6.186.3
       serial: None
       slot: U3E1
       size: 2194MHz
       capacity: 4600MHz
       width: 64 bits
       clock: 100MHz
       capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect user_shstk avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr ibt flush_l1d arch_capabilities cpufreq
       configuration: cores=10 enabledcores=10 microcode=16673 threads=12
```

The gpu is not detected in `clinfo` either. `clinfo` installed on the host does not detect either (my user is in `render` and `video` groups). 

My setup hasn't changed (reproducible using the docker image and instructions at https://github.com/soda-inria/sklearn-numba-dpex?tab=readme-ov-file#using-the-docker-image), it doesn't work either after upgrading all drivers to latest versions.

**Comment by fcharras** [comment]
More information on my packages:

In the docker container:

```
root@4d14ca598997:~# dpkg --list | grep intel
ii  intel-igc-cm                1.0.144+i75~u20.04                      amd64        Intel(R) C for Metal Compiler -- CM Frontend lib
ii  intel-igc-core              1.0.15985.7                             amd64        Intel(R) Graphics Compiler for OpenCL(TM)
ii  intel-igc-media             1.0.15985.7                             amd64        Intel(R) Graphics Compiler for OpenCL(TM)
ii  intel-igc-opencl            1.0.15985.7                             amd64        Intel(R) Graphics Compiler for OpenCL(TM)
ii  intel-igc-opencl-devel      1.0.15985.7                             amd64        Intel(R) Graphics Compiler for OpenCL(TM)
ii  intel-level-zero-gpu        1.3.28454.6                             amd64        Intel(R) Graphics Compute Runtime for oneAPI Level Zero.
ii  intel-media-va-driver:amd64 22.3.1+dfsg1-1ubuntu2                   amd64        VAAPI driver for the Intel GEN8+ Graphics family
ii  intel-opencl-icd            24.05.28454.6                           amd64        Intel graphics compute runtime for OpenCL
ii  libdrm-intel1:amd64         2.4.113-2~ubuntu0.22.04.1               amd64        Userspace interface to intel-specific kernel DRM services -- runtime
```

On the host:

```
$ pacman -Qs intel
local/intel-compute-runtime 23.48.27912.11-1
    Intel(R) Graphics Compute Runtime for oneAPI Level Zero and OpenCL(TM) Driver
local/intel-gmmlib 22.3.17-1
    Intel Graphics Memory Management Library
local/intel-graphics-compiler 1:1.0.15610.11-1
    Intel Graphics Compiler for OpenCL
local/intel-ucode 20240312-1
    Microcode update files for Intel CPUs
local/lib32-vulkan-intel 1:24.0.3-1
    Intel's Vulkan mesa driver (32-bit)
local/libmfx 23.2.2-2
    Intel Media SDK dispatcher library
local/libvpl 2.10.2-1
    Intel Video Processing Library
local/vulkan-intel 1:24.0.3-1
    Intel's Vulkan mesa driver
```

and the kernel version:

```
$ uname -a
Linux fcprobabl 6.8.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000 x86_64 GNU/Linux
```

**Comment by oleksandr-pavlyk** [comment]
@fcharras I think we need to first figure out the issue on the host OS, and then proceed to docker. 

Per https://www.intel.com/content/www/us/en/products/sku/232153/intel-core-i51335u-processor-12m-cache-up-to-4-60-ghz/specifications.html, your system should have Iris Xe, with GPU Device ID `0xA7A1`.  

Per https://cateee.net/lkddb/web-lkddb/DRM_I915.html, this device is supported by Linux kernel versions 5.9, 6.0-6.8, so we are good here,

You can confirm that Device ID is correct by running `lspci -knn | grep -A8 VGA`. The output would also tell you where `i915` driver is in use. On my system a line `"Kernel driver in use: i915"` is present. 

Next, check that `renderD*` device is present by outputting `ls -l /dev/dri`.  If present, note that `renderD*` has group permission of group `render`. You must belong to this group to interact with the device. Check output of `groups` to ensure that you are.

If you are a member of this group, but the device is not visible, inspect the output of `sudo dmesg` for errors from `i915` driver. 

Let's see what you find before proceeding any further.

**Comment by fcharras** [comment]
The following seems good:

```$ ls /dev/dri/
by-path  card1  renderD128
```

```
$ groups $USER
sys wheel render video [...]
```
(I also just rebooted computer in case it makes a difference after registering the new group)

Also this, but it shows `8086:a7a1` rather than `0xA7A1`:
```
$ lspci -knn | grep -A8 VGA
00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-P [Iris Xe Graphics] [8086:a7a1] (rev 04)
	Subsystem: Lenovo Raptor Lake-P [Iris Xe Graphics] [17aa:2315]
	Kernel driver in use: i915
	Kernel modules: i915, xe
```

no particular error in `dmesg`:

```$ sudo dmesg | grep i915
[   10.946375] i915 0000:00:02.0: enabling device (0006 -> 0007)
[   10.949342] i915 0000:00:02.0: [drm] VT-d active for gfx access
[   11.000103] i915 0000:00:02.0: vgaarb: deactivate vga console
[   11.000184] i915 0000:00:02.0: [drm] Using Transparent Hugepages
[   11.000661] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=io+mem:owns=mem
[   11.003517] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adlp_dmc.bin (v2.20)
[   11.013504] mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_ops [i915])
[   11.060687] i915 0000:00:02.0: [drm] GT0: GuC firmware i915/adlp_guc_70.bin version 70.20.0
[   11.060707] i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
[   11.077211] i915 0000:00:02.0: [drm] GT0: HuC: authenticated for all workloads
[   11.077862] i915 0000:00:02.0: [drm] GT0: GUC: submission enabled
[   11.077868] i915 0000:00:02.0: [drm] GT0: GUC: SLPC enabled
[   11.078322] i915 0000:00:02.0: [drm] GT0: GUC: RC enabled
[   11.080199] mei_pxp 0000:00:16.0-fbf6fcf1-96cf-4e2e-a6a6-1bab8cbe36b1: bound 0000:00:02.0 (ops i915_pxp_tee_component_ops [i915])
[   11.080746] i915 0000:00:02.0: [drm] Protected Xe Path (PXP) protected content support initialized
[   12.296223] [drm] Initialized i915 1.6.0 20230929 for 0000:00:02.0 on minor 1
[   12.301030] i915 display info: display version: 13
[   12.301034] i915 display info: cursor_needs_physical: no
[   12.301037] i915 display info: has_cdclk_crawl: yes
[   12.301038] i915 display info: has_cdclk_squash: no
[   12.301040] i915 display info: has_ddi: yes
[   12.301041] i915 display info: has_dp_mst: yes
[   12.301043] i915 display info: has_dsb: yes
[   12.301044] i915 display info: has_fpga_dbg: yes
[   12.301045] i915 display info: has_gmch: no
[   12.301046] i915 display info: has_hotplug: yes
[   12.301048] i915 display info: has_hti: no
[   12.301049] i915 display info: has_ipc: yes
[   12.301050] i915 display info: has_overlay: no
[   12.301051] i915 display info: has_psr: yes
[   12.301053] i915 display info: has_psr_hw_tracking: no
[   12.301054] i915 display info: overlay_needs_physical: no
[   12.301055] i915 display info: supports_tv: no
[   12.301056] i915 display info: has_hdcp: yes
[   12.301058] i915 display info: has_dmc: yes
[   12.301059] i915 display info: has_dsc: yes
[   12.304129] fbcon: i915drmfb (fb0) is primary device
[   12.304066] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   12.327206] i915 0000:00:02.0: [drm] fb0: i915drmfb frame buffer device
[   13.114828] i915 0000:00:02.0: [drm] Selective fetch area calculation failed in pipe A
```

**Comment by fcharras** [comment]
Here's attached the output of `LD_DEBUG=libs clinfo >& ld_log.txt` in container and host.
[container.txt](https://github.com/IntelPython/dpctl/files/14668544/container.txt)
[host.txt](https://github.com/IntelPython/dpctl/files/14668545/host.txt)

**Comment by oleksandr-pavlyk** [comment]
@fcharras Please let me know whether you were able to resolve the issue by reinstalling GPU drivers, or whether this is a viable route at all. Thanks!

**Comment by ogrisel** [comment]
> I would uninstall Debian packages pertaining to the GPU from your host machine

I don't understand how this is possible. The host machine is an Arch linux machine. The packages are listed in the second part of https://github.com/IntelPython/dpctl/issues/1600#issuecomment-2009631935 (with the `pacman` command).

**Comment by ogrisel** [comment]
Similarly, trying to override the pacman packages of an Arch system debian packages designed for Ubuntu system risk breaking the host, no?

**Comment by fcharras** [comment]
Actually someone is maintaining a community [`intel-compute-runtime`](https://aur.archlinux.org/packages/intel-compute-runtime-bin) package that directly sources from the deb packages in intel/compute-runtime repo (see [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=intel-compute-runtime-bin)).

Unfortunately it doesn't fix the issue.

Now I wonder if it could be that my hardware is faulty.

I could try to boot an ubuntu system from a usb flash drive to see if I can get it work :thinking:

**Comment by oleksandr-pavlyk** [comment]
@fcharras It was suggested that a useful thing to try is to run `strace -o strace.log clinfo` and provide the log, please.

**Comment by oleksandr-pavlyk** [comment]
@fcharras Ping

**Comment by fcharras** [comment]
Thanks for your help @oleksandr-pavlyk 

Here are attachments of strace logs when running `clinfo` both on host or in the container:

- on the host: [strace.log](https://github.com/IntelPython/dpctl/files/14956029/strace.log)

- in the container: [strace-container.log](https://github.com/IntelPython/dpctl/files/14956050/strace-container.log)

**Comment by fcharras** [comment]
I tried booting from a 22.04 ubuntu usb flash drive and followed https://dgpu-docs.intel.com/driver/client/overview.html, and there clinfo does detect the gpu. So it's not a hardware issue.

Unfortunately I couldn't test the docker image from the usb flash drive because of lack of storage space in the usb flash drive environment to download the image.

However applying instructions from https://dgpu-docs.intel.com/driver/client/overview.html inside the container from my arch linux host does not fix the issue.

My (perhaps limited) understanding of how docker containerization works is that it shares kernel and kernel modules configuration with the host but everything else (the runtime libraries level) is superseded by libraries inside the container. The runtime installation instructions at https://dgpu-docs.intel.com/driver/client/overview.html (skipping the `Optional Out-of-Tree Kernel-Mode Driver Install` section that is said to be optional, and that I also skipped during tests on ubuntu 22.04 from the flash drive) does not use DKMS, is it enough to conclude that is consists only in libraries that will supersede host libraries when running inside a container ? If so, since it happens both on the host and in the container, the issues I encounter with my arch-based distro and gen13 laptop maybe hint that there's something wrong with the kernel that is shipped, or that some kernel module might be missing ?

Are there instructions I could run to check compatibility of my kernel (or my set of kernel modules) with gen13 gpu ?

**Comment by fcharras** [comment]
Now it's not quite a `dpctl` issue, but there are a few somewhat popular arch-based distributions (vanilla arch linux, endeavor os, garuda os, manjaro) and I'm a long time user myself so I would be very happy to manage to make it work there :smiley_cat: inside a docker container would be a good start, but on the host would be nice too.

**Comment by fcharras** [comment]
Thank you @oleksandr-pavlyk this was the same issue indeed and this fix works.

The release of the compute runtime that ships the permanent fix for recent kernels has just been released (cf https://github.com/intel/compute-runtime/issues/710#issuecomment-2047830413 ).

**Comment by fcharras** [comment]
> Actually someone is maintaining a community [`intel-compute-runtime`](https://aur.archlinux.org/packages/intel-compute-runtime-bin) package that directly sources from the deb packages in intel/compute-runtime repo (see [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=intel-compute-runtime-bin)).

Also worth mentioning that this is up to date and has been bumped with the fixes, clinfo properly works on the host too now without requiring the environment variabls :-)
