### ISSUE TITLE
Create a user guide for dpctl queue management and add it to our documentation site.

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#164]
Along with examples, we need to define the spec of dpctl's queue manager. The spec is complementary to API documentation on our GH-pages.

**Comment by PokhodenkoSA** [comment]
@diptorupd What is the status of this issue? Queue manager is updated now.

**Comment by diptorupd** [comment]
Still in progress. I will get to it after the release.

**Comment by oleksandr-pavlyk** [comment]
@diptorupd I suppose we should close this as the feature queue manager is deprecated.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk sure.
