### ISSUE TITLE
Shape setter does not work with negative shape

### ISSUE THREAD

**Issue by antonwolfy** [IntelPython/dpctl#1699]
The below example reproduces an issue with passing negative shape to the setter:
```python
import numpy, dpctl, dpctl.tensor as dpt

dpctl.__version__
Out: '0.18.0dev0+21.g60fc3eb9d0'

a = dpt.ones(4)
a.shape = [-1]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 a.shape = [-1]

File dpctl/tensor/_usmarray.pyx:582, in dpctl.tensor._usmarray.usm_ndarray.shape.__set__()

TypeError: Can not reshape array of size 4 into (-1,)
```
but works with positive shape and with `reshape` and in numpy:
```python
a = dpt.ones(4)

a.shape = [4]
dpt.reshape(a, [-1])

a = numpy.ones(4)
a.shape = [-1]
```

**Comment by oleksandr-pavlyk** [comment]
Documentation string for shape setter specifies that only non-negative values are supported, and suggests to use `tensor.reshape` if negative values are needed.  I suggest to close this issue.

**Comment by antonwolfy** [comment]
@oleksandr-pavlyk, thank you for the support.
The dpctl documentation is clear now regarding supported values by `shape.setter` in `usm_ndarray`.
