### ISSUE TITLE
Transition dpctl CI to use clang-format-18

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [IntelPython/dpctl#1708]
We currently use clang-format from Ubuntu 20.04 (clang-format-11), it is time to transition to clang-format from Ubuntu 24.04 (clang-format-18).

This would require either adapting format config file to keep sources unchanged, or changing source in one swoop commit and add it to `.gitblame`.

**Comment by ZzEeKkAa** [comment]
Should we rely on conda package instead of ubuntu's built in packages to meet cross system compatibility?
