### ISSUE TITLE
dpctl should generate C headers for use of dpctl Python objects with Python C-API

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [IntelPython/dpctl#171]
Torch extensions are built in C++ with use of pybind11 (c.f. [custom-c++-torch-extensions](https://pytorch.org/tutorials/advanced/cpp_extension.html)).

One may want to recognize and work with `SyclQueue`, `SyclDevice`, and `SyclContext` objects, which requires a header.

Cython allows for generation of such headers: https://stackoverflow.com/questions/5710441/call-cython-function-from-c

**Comment by oleksandr-pavlyk** [comment]
Here is a discussion on SO: https://stackoverflow.com/questions/40572073/how-to-create-a-public-cython-function-that-can-receive-c-struct-instance-or-p 

I adapted example written by @pelson based on suggestion in that SO post to Python3 and use in conda environment: https://github.com/oleksandr-pavlyk/calling_publicly_declared_cython_from_c

**Comment by oleksandr-pavlyk** [comment]
Another useful repo: https://github.com/ashwinvis/cython_capi

**Comment by diptorupd** [comment]
@oleksandr-pavlyk was this issue addressed by #218?

**Comment by diptorupd** [comment]
@oleksandr-pavlyk is going to add an example and close the issue.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk ping!

**Comment by oleksandr-pavlyk** [comment]
Will work on this next week. Changes in #218 should have been sufficient, but having an example is both a proof of that and a seed to promote adoption

**Comment by diptorupd** [comment]
@oleksandr-pavlyk I believe the ticket can be closed?

**Comment by oleksandr-pavlyk** [comment]
What is still missing is a single `"dpctl.h"` to include to work with Python C-API of `dpctl` classes. 

I think we should also have the same single header `"syclinterface.h"`.

**Comment by oleksandr-pavlyk** [comment]
This has now been implemented in #685. Closing.
