### ISSUE TITLE
Consider new ways to call CMake

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#173]
I thought this PR would build on Python's interface to CMake:

https://github.com/pytorch/pytorch/blob/master/tools/build_pytorch_libs.py#L51

Kind of like 

https://github.com/pytorch/pytorch/blob/master/tools/setup_helpers/cmake.py#L94

Maybe a little too heavy-handed for our purposes.

_Originally posted by @oleksandr-pavlyk in https://github.com/IntelPython/dpctl/pull/168#issuecomment-723198177_

**Comment by diptorupd** [comment]
@oleksandr-pavlyk I think you latest design using `scikit-build` will subsume this ticket. I am assigning it to you for that reason.

**Comment by diptorupd** [comment]
Closing as we now use `skbuild` to invoke `Cmake`.
