### ISSUE TITLE
Cannot install using conda

### ISSUE THREAD

**Issue by chillenb** [IntelPython/dpctl#1734]
What happened to Intel's channel on Anaconda?

```
$ conda install dpctl -c intel
Channels:
 - intel
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

**Comment by oleksandr-pavlyk** [comment]
Due to a change in Anaconda policy, channel '-c intel' which is perceived by Anaconda as an enterprise channel, was disabled due to disagreements on the terms of use.

Please replace "-c intel" with "-c https://software.repos.intel.com/python/conda"

See gh-1729 and gh-1737 for more details.

**Comment by chillenb** [comment]
Thanks for the clarification!!

Does it look like this will be a permanent change, or will there be further attempts to resolve things with Anaconda?

**Comment by oleksandr-pavlyk** [comment]
> Does it look like this will be a permanent change, or will there be further attempts to resolve things with Anaconda?

FYI, related question https://github.com/IntelPython/numba-dpex/issues/1480  . 

As far as I am aware I would not expect a near-term resolution, but I am ready to be surprised

**Comment by oleksandr-pavlyk** [comment]
@chillenb Can this issue be closed now?

**Comment by chillenb** [comment]
Sure. Thanks for your help
