### ISSUE TITLE
Build Cython modules with default compiler (not DPC++)

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#174]
I think next step (in another PR) should be to try allow Python to build Cython modules with default compiler (not DPC++).
DPC++ is needed only in backend.

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/dpctl/pull/168#r521893268_

**Comment by diptorupd** [comment]
@PokhodenkoSA I fixed this a while back in our `setup.py`. Can you confirm?

**Comment by PokhodenkoSA** [comment]
@diptorupd could you please attach PR with which you fixed this issue?

**Comment by diptorupd** [comment]
We originally were setting the `CC` and `CXX` to `dpcpp` in the `build.sh`. #168 removed the `CC` and `CXX` from build.sh, but added these two lines to the `setup.py`
```
    os.environ["CC"] = DPCPP_ROOT + "/bin/clang"
    os.environ["CXX"] = DPCPP_ROOT + "/bin/clang++"
```
#270 removed these two lines so that we do not use `dpcpp` to build the cython extensions.

**Comment by PokhodenkoSA** [comment]
Then I think it could be closed.
