### ISSUE TITLE
Utility script dpctl

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#181]
There is convenient command in Numba: `numba -s` which shows all useful information about environment.
If we will provide similar script like `dpctl -s` which will show available devices
then it would be more convenient than using `python -c "import dpctl; dpctl.dump()"`.

/CC @diptorupd

**Comment by diptorupd** [comment]
@PokhodenkoSA Sure why not.

**Comment by diptorupd** [comment]
I do not think anyone is going to work on it, and since the feature has not been required in all this time it maybe was not that critical. It was still a good idea though.
