### ISSUE TITLE
Examples are out of date

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#187]
No `runtime` package in `dpctl`.

/CC @densmirn

**Comment by oleksandr-pavlyk** [comment]
Please see branch examples-added

**Comment by PokhodenkoSA** [comment]
As I can see this branch contains update for `examples/python/create_sycl_queues.py`.
If work in `examples-added` is not ready yet (I did not find any PR for it) we could split changes in `examples/python/create_sycl_queues.py` into separate PR and merge it. So dpCtl will have correct examples. Future work in the `examples-added` could be continued as needed.

**Comment by oleksandr-pavlyk** [comment]
Please see #197
