### ISSUE TITLE
Tests for NumPy could be run with dptensor.numpy_usm_shared as replacement for np

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#188]
We need to find a way to run this tests.

/CC @DrTodd13

**Comment by PokhodenkoSA** [comment]
Variants:
1. Copy tests from NumPy. Create dparray and pass to NumPy functions.
2. Write own tests for basic functions. Create dparray and pass to some NumPy functions (i.e. sin() and cos())
3. See Xtensor approach to test with NumPy compatibility.

**Comment by diptorupd** [comment]
Closing as `numpy_usm_shared` is going to be deprecated and removed in some future release.
