### ISSUE TITLE
Check dpctl.device context manager design against issues in pytorch device context manager

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [IntelPython/dpctl#190]
This is a task to review and understand issues in PyTorch's device context manager (pytorch/pytorch#27878). 

Also see data-apis/array-api#39

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Do we need to keep this issue open?

**Comment by oleksandr-pavlyk** [comment]
No, closing.
