### ISSUE TITLE
Using __array_interface__ instead of adding __sycl_usm_array_interface__

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#191]
Using 2 properties `__array_interface__` and `__sycl_usm_array_interface__` in dparray requires 2 checks in downstream libraries.
Performance penalty.
Related to #184.

/CC @oleksandr-pavlyk @shssf

**Comment by oleksandr-pavlyk** [comment]
These two properties serve different purposes, and can not be combined. One does not have to check for both. Please clarify what performance penalty you have in mind.

**Comment by PokhodenkoSA** [comment]
> different purposes

Does it mean that we will always know exactly which property we need?


> Please clarify what performance penalty you have in mind.

Double checking both properties. One for SYCL queue (`__sycl_usm_array_interface__`) and another for fallback to usual `__array_interface__` is the first is not available.

**Comment by PokhodenkoSA** [comment]
I know this cases from dpNP and @shssf.
Also I have asked @DrTodd13 about this new property.
Just want to know the reasons behind introducing this property and comparing to other variants (i.e. extend `__array_interface__` dict with new items).

**Comment by oleksandr-pavlyk** [comment]
NumPy checks for `__array_interface__` trying to recognize a Python object as a ["duck-array"](https://github.com/numpy/numpy/blob/92bf2f6d81252f97a7acc69fcc016636b29d1277/numpy/core/src/multiarray/ctors.c#L1255), also known as "array-like" . This property has been largely superseded by Python buffer protocol.  

Python objects backed by USM memory export `__sycl_usm_array_interface__` to be recognized as carriers of USM memory.

**Comment by diptorupd** [comment]
Closing since @oleksandr-pavlyk's comments explains the rationale of why the two attributes are needed.
