### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#196]
- [x] https://github.com/IntelPython/dpctl/pull/224
- [x] Update change log
- [x] Update gh-pages

CHANGELOG:
Add:
* dparray
* USM
* Examples https://github.com/IntelPython/dpctl/pull/197
* Documentation improvements https://github.com/IntelPython/dpctl/pull/224

Change:
* Rename DPPL to DPCTL #201
* Moved SyclProgram and SyclKernel out of dpctl into dpctl.program #199

**Comment by diptorupd** [comment]
Added examples

**Comment by diptorupd** [comment]
renamed DPPL to DPCTL.

**Comment by diptorupd** [comment]
Moved SyclProgram and SyclKernel out of dpctl into dpctl.program #199

**Comment by diptorupd** [comment]
@PokhodenkoSA I have updated the documentation files (#224 ) a bit to match the upcoming 0.5.0 release. #224 should be merged before the release. We will update the gh-pages after the release so that the version is displayed correctly in the Sphinx pages.

**Comment by diptorupd** [comment]
documentation is now up-to-date.
