### ISSUE TITLE
Run examples in CI

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#198]
Related https://github.com/IntelPython/dpctl/pull/197

Examples now are checked only manually. CI will help to fix regressions in examples.

- [ ] Modify scripts for running Python examples in CI
- [ ] Building and running Cython examples

**Comment by diptorupd** [comment]
@oleksandr-pavlyk The issue is worth resolving. The idea is to keep our examples up to date and we can add a Github workflow to do it.

**Comment by oleksandr-pavlyk** [comment]
@diptorupd We [do test examples](https://github.com/IntelPython/dpctl/blob/master/.github/workflows/conda-package.yml#L362) on Linux in `conda-package.yml`.

![image](https://user-images.githubusercontent.com/21087696/195067966-79e97377-2804-44a4-b718-ac190c49ea9b.png)
