### ISSUE TITLE
SYCL functionalities

### ISSUE THREAD

**Issue by zjin-lcf** [IntelPython/dpctl#2]
May you please use some examples to demonstrate that the lightweight Python package exposes a subset of SYCL functionalities ?

Thanks

**Comment by diptorupd** [comment]
@zjin-lcf Sorry for the late response. 

The library is as you can see still very early in terms of development. At this point the the only functionality that is present here is to expose a queue manager for sycl::queue objects. We will soon add support for sycl::program, usm allocators and sycl::buffer objects.

**Comment by diptorupd** [comment]
@PokhodenkoSA Linked to #32. Once our API documentation is online we can close the ticket.

**Comment by PokhodenkoSA** [comment]
#197 provides more examples.
@zjin-lcf If you will not find what you need, please, reopen this issue.

**Comment by zjin-lcf** [comment]
Thanks for your updates.
