### ISSUE TITLE
Remove line with file name and other from headers of all files

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#203]
I do not like this line. It duplicates file name and also it lies about Cython. Conclusion: unnecessary support costs.
Lets keep only License at the header of the file and docstring with description of the content.

For Python code content description line should be in format for docstring.
For C++ code content description line should be in format for doxygen.

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/dpctl/pull/202#discussion_r536755170_

**Comment by diptorupd** [comment]
https://llvm.org/docs/CodingStandards.html#file-headers is what I was following. So, I do not agree removing these from the C/C++ files. The exact coding format `-*-...-*-` is not followed correctly in many places and I will fix them. If a project like LLVM can maintain the headers without them being an overhead it should not be a big deal for us as well.

If we do not want them in Python/Cython code we can remove them.
