### ISSUE TITLE
Complete the implementation of `dpctl.dptensor.numpy_usm_shared.ndarray.__array_ufunc__`

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#207]
The current implementation of `dpctl.dptensor.numpy_usm_shared.ndarray.__array_ufunc__` only implements the `__call__` function and not the other needed dunder methods: `__reduce__`, `__reduceat__`, `__accumulate__`, `__outer__`. These other methods have to be implemented to complete the `__array_ufunc__` implementation.

**Comment by PokhodenkoSA** [comment]
@oleksandr-pavlyk Did you take this issue?

**Comment by PokhodenkoSA** [comment]
Who could take this issue?

**Comment by diptorupd** [comment]
@oleksandr-pavlyk do you have bandwidth for this task? If not, can guide someone on what needs to be done?

**Comment by diptorupd** [comment]
It is still relevant, but unlikely to be fixed as `numpy_usm_shared` is in maintenance mode and will be deprecated once `dpctl.tensor.usm_ndarray` is feature complete.

**Comment by oleksandr-pavlyk** [comment]
`numpy_usm_shared` has been removed.
