### ISSUE TITLE
Improve documentation of the numpy_usm_shared module

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#208]
We should add 

- [ ] a module-level doctring with examples.
- [ ] class level docstrings in ndarray with examples.
- [ ] `from_ndarray` and `as_ndarray` functions
- [ ] include the docs into `dpctl` sphinx docs

**Comment by PokhodenkoSA** [comment]
@diptorupd Is it possible to make it for the current release?

**Comment by diptorupd** [comment]
It will still be good to do, but I do not see it happening. `numpy_usm_shared` is in maintenance mode and will be deprecated once `dpctl.tensor.usm_ndarray` is feature complete. 
As such closing as `WONTFIX`
