### ISSUE TITLE
Reevaluate all function and member names inside `numpy_usm_shared`

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#209]
We should used leading underscores for all function and member names that are not intended to be exposed as part of the public API.

**Comment by PokhodenkoSA** [comment]
@diptorupd Is it possible to make it for the current release?

**Comment by diptorupd** [comment]
Should be a small task, but I may not get to it.

**Comment by diptorupd** [comment]
Closing as `WONTFIX`. `numpy_usm_shared` is under maintenance mode and will be deprecated once `dpctl.tensor.usm_ndarray` is more feature complete.
