### ISSUE TITLE
dpctl.version and dpctl.version.version

### ISSUE THREAD

**Issue by shssf** [IntelPython/dpctl#212]
It might be great to implement version variable in the package.
Currently I see:
```
(base) sshalnov@shssf-home:/home/work/dpnp$ python -c "import numpy as sw; print(f\"sw.version={sw.version}\nsw.version.version={sw.version.version}\")"
sw.version=<module 'numpy.version' from '/home/work/anaconda3/lib/python3.7/site-packages/numpy/version.py'>
sw.version.version=1.19.2
```
and from the same script but with `dpctl`:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'dpctl' has no attribute 'version'
```
Sorry if I missed something.

**Comment by PokhodenkoSA** [comment]
@shssf please use this: `dpctl.__version__`
It is provided by versioneer tool. There is documentation inside it: https://github.com/IntelPython/dpctl/blob/master/versioneer.py

**Comment by diptorupd** [comment]
@PokhodenkoSA is this issue resolved? `numpy.version` predates versioneer and we most probably do not want to implement the `version` module?

**Comment by PokhodenkoSA** [comment]
Reopen if neede.
