### ISSUE TITLE
Update README section about using setup.py

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#215]
Section: https://github.com/IntelPython/dpctl#build-and-install-with-setuptools
It should contain which packages should be installed:
- cmake
- ninja - for Windows only
- cython
- numpy - optionally?

It is necessary to verified this list on Linux and Widows.

**Comment by oleksandr-pavlyk** [comment]
`cython`, `cmake` and `numpy` are required dependencies on all platforms. `ninja` is required on Windows only.
