### ISSUE TITLE
No tests for `add_external_usm_checker()`.

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#216]
No tests for `add_external_usm_checker()`.

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/dpctl/issues/214#issuecomment-743143452_

**Comment by diptorupd** [comment]
This is related to `dptensor.numpy_usm_shared` that is going to be deprecated in favor of `usm_array` in two weeks from when @oleksandr-pavlyk starts working on it :)

**Comment by oleksandr-pavlyk** [comment]
@diptorupd `dpctl.dptensor` has been renamed into `dpctl.tensor`, the `dpctl.tensor.numpy_usm_shared` stays for now, and `dpctl.dptensor.usm_ndarray` has been added.

Does this issue merit staying open?

**Comment by diptorupd** [comment]
I am closing the ticket as WONTFIX. The `dpctl.tensor.numpy_usm_shared` is a piece of legacy code that still exists due to Numba-dpex using the module. As soon as dpex switches to compute follows data the module can be removed.
