### ISSUE TITLE
Add example for demonstration of integration dpctl in other libraries

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#219]
Requested from dpnp and daal4py.

/CC @shssf @Alexander-Makaryev @napetrov

**Comment by oleksandr-pavlyk** [comment]
`dpctl` provides data container,`dpctl.tensor.usm_ndarray`, and a set of operations to operate on it as specified in Python Array API standard. 

`dpnp` builds on such a container, and so does `scikit-learn-intelex`
