### ISSUE TITLE
Not working dpCtl API documentation

### ISSUE THREAD

**Issue by akharche** [IntelPython/dpctl#223]
Tried to build documentation based on provided [instructions](https://github.com/IntelPython/dpctl/blob/master/docs/README.md). Several problems were detected:

1. I can not install package [exhale](https://github.com/svenevs/exhale) via pip or conda. Conda pckgs are not provided, pip gives the error:   
`ERROR: Could not find a version that satisfies the requirement exhale` 
2. The command line in the documentation does not work:  
` mkdir build cd build cmake -DDPCTL_DOCGEN_PREFIX=<WHERE_YOU_WANT_DOCS_TO_BE_GENERATED> make Sphinx` 
Changes to:  
```bash
mkdir build cd build 
cmake .. -DDPCTL_DOCGEN_PREFIX=<WHERE_YOU_WANT_DOCS_TO_BE_GENERATED>
make
```  
And it fails due to missing exhale package

**Comment by diptorupd** [comment]
@akharche I managed to get `exhale` (https://pypi.org/project/exhale/) from pip. I am pretty sure I previously managed to install it from conda too, but you are right currently `conda install exhale` fails. I wonder what changed?

**Comment by akharche** [comment]
@diptorupd After several tries I've found that something wrong with my conda environment and pip failed to install any package. So, finally I built docs, but there is an addition dependency: `sphinx_rtd_theme`.

**Comment by diptorupd** [comment]
@akharche can we close this ticket?

**Comment by akharche** [comment]
#226
