### ISSUE TITLE
Enable pre-commit hooks for fast local checks during development

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#237]
Examples:
- pandas - https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#contributing-pre-commit
- https://gitlab.com/daverona/pre-commit/cpp/-/blob/master/.pre-commit-hooks.yaml

**Comment by diptorupd** [comment]
We now have pre-commit hooks for `black`, `isort`, `flake8`, `bandit`, `clang-format`, trailing white spaces, newline at EOF.
