### ISSUE TITLE
Remove build_for_develop.(bat|sh) files from scripts folder

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#239]
In `scripts` folder there are build files for developers but not all developers use it:
- https://github.com/IntelPython/dpctl/blob/master/scripts/build_for_develop.bat
- https://github.com/IntelPython/dpctl/blob/master/scripts/build_for_develop.sh

As we have now possibility to use `python setup.py develop` (#145) for build all necessary things via setup.py, can we remove this files?
If this files contain some feature like building in debugging mode or running tests for backend then we could move this features to setup.py script too.

Sometimes developers think that this files are reference of how dpCtl is built. It leads to wrong understanding of dpCtl build procedure.

@diptorupd @reazulhoque @1e-to @vlad-perevezentsev @shssf

**Comment by diptorupd** [comment]
@PokhodenkoSA Currently the only thing extra the scripts at least on linux is a way to run the test suite for Python and Ctest. I think everything else is there.

**Comment by oleksandr-pavlyk** [comment]
I second @diptorupd in vote to keep the script around.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk revisiting the issue after almost a year. All the infrastructure improvements that have happened since then means I have not used these scripts in a very long time. Time to remove them?

**Comment by diptorupd** [comment]
Done.
