### ISSUE TITLE
Public CI

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#243]
Public CI goals:
- Backup for internal CI
- [x] Test in different environments (py37, py38, py39)
- Use only publicly available packages
- Show example code for building the package (/CC @shssf)
- [x] Upload master branch packages to `intel/label/dev` channel

Use Azure pipelines or GitHub Actions.

Possible problems:
- Not all packages available on public intel channel
- Long downloading of oneAPI
- Slow CI (>10mins)

**Comment by PokhodenkoSA** [comment]
Links:
- https://github.com/actions/virtual-environments - GitHub Actions machines

**Comment by diptorupd** [comment]
It was implemented a while back.
