### ISSUE TITLE
Support for multi-GPU machines (sort devices by performance)

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#246]
Features:
- [x] select which GPU to use
- [ ] sort GPUs for selecting fastest as default

**Comment by diptorupd** [comment]
The first feature request "select which GPU to use" was implemented recently and will be part of 0.7. We can use `DPC++`'s `SYCL_DEVICE_FILTER` environment variable to control what SYCL devices are not rejected by the runtime.

The second feature about selecting fasted device is outside the scope of dpctl. In CUDA, the CUDA runtime provides the functionality to select fastest device and limits which devices are visible. If a similar feature is needed, `DPC++` will have to provide the functionality. However, using device enumeration and device properties a user can potentially design such a device selection logic in dpctl.

Closing the issue. Please reopen if needed.
