### ISSUE TITLE
Functions for selecting current device

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#247]
Now current device is changed via `dpctl.device_context`. Internally it changes current device at enter to context and return previous device on exit from context. Functions for changing current device should be provided in API.

Functions:
- [ ] select_device
- [ ] close

Also functions could provide access to internal contexts stack.

**Comment by diptorupd** [comment]
@PokhodenkoSA can you clarify what exactly needs to be done here? The concept of default queue is going to go away from `dpctl`. Instead we can make the `dpctl._SyclQueueManager` class public and `numba-dppy` can use it to manage a current queue for numba-dppy. 

Also, the recent changes that got merged into master adds an API call `dpctl.set_global_queue` to change the current queue without having to use a `with dpctl.device_context`. The function previously existed as `dpctl.set_default_queue`.

**Comment by PokhodenkoSA** [comment]
@diptorupd I propose to meet and discuss it.

**Comment by diptorupd** [comment]
The device manager has been significantly modified to let users create SYCL devices as they wish. The notion of current device is deprecated and we will not have the feature in dpctl eventually. @oleksandr-pavlyk Fine with closing the issue?

**Comment by oleksandr-pavlyk** [comment]
Vote to close.

**Comment by oleksandr-pavlyk** [comment]
Explicit creation of devices/queues. 

* `dpctl.SyclDevice()` gives default selected device
* `dpctl.SyclQueue()` gives queue constructed from default selector.
* `dpctl.SyclQueue(filter_string)` constructs sycl queue from given filter selector string.

**Comment by diptorupd** [comment]
Closing as the design based on a "current device" has been removed and the device manager code is also slotted to be removed.
