### ISSUE TITLE
Support IPC for Device Memory

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#249]
Features:
- [ ] Create IPC handle for Device Memory
- [ ] Serialize IPC handle
- [ ] Open IPC handle - Get Device Memory from IPC handle
- [ ] Close IPC handle
- [ ] Context manager for open/close for IPC handle

**Comment by diptorupd** [comment]
Not related to dpctl. The issue was identified as a gap between numba.cuda functionality and numba-dpex. However, device memory IPC is not used at the level of numba-dpex and dpctl. Instead, such lower level functions are not exposed to users.
