### ISSUE TITLE
Implement Memory Info

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/dpctl#257]
If an implementation of get_memory_info() is to provide a result, then it should return an instance of the MemoryInfo named tuple

**Comment by oleksandr-pavlyk** [comment]
Could you please elaborate? `get_memory_info` is a stand-alone function, a method of a class (which?), etc.

**Comment by diptorupd** [comment]
@1e-to @PokhodenkoSA can you provide some context or reference to Numba.cuda code?

**Comment by PokhodenkoSA** [comment]
@1e-to please, provide more context for the issue.

**Comment by diptorupd** [comment]
`MemoryInfo` is an internal numba data structure and I do not foresee us implementing a function to return such an object in dpctl. Memory allocators defined by `dpctl.memory` can be used to create a `MemoryInfo` if needed, as is done by numba-dppy.
