### ISSUE TITLE
Naming convention for C API

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#278]
@oleksandr-pavlyk  @PokhodenkoSA  @reazulhoque  We need to decide what should be the naming standard we follow for our C API functions and types. The current way `DPCTL##TY##_##FN##()` is basically neither here nor there.

Should we go to small case C style names?
`dpctl_##ty##_##fn()`

Or, perhaps to camel case?

**Comment by reazulhoque** [comment]
May be [this](https://stackoverflow.com/a/1722518)?

**Comment by diptorupd** [comment]
Closing in favour of #330.
