### ISSUE TITLE
Implement get_backend, get_platform, get_backend_info

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/dpctl#291]
Proposed names: 
- [x] DPCTLDevice_GetBackend()
- [x] DPCTLDevice_GetPlatform()
- [ ] DPCTLDevice_GetBackendInfo()

**Comment by diptorupd** [comment]
@1e-to  DPCTLDevice_GetBackend() and  DPCTLDevice_GetPlatform() are implemented and merged in #300.

**Comment by diptorupd** [comment]
`get_backend_info` is out  of scope for us for now.
