### ISSUE TITLE
Improve the print info functions

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/dpctl#293]
~~- [ ] The device print info functions in both C and Python should support printing all info and aspects.~~
~~- [ ] The functions should have a "less" option to limit the amount of descriptors that are printed. By default, the less option should be turned on and only print a limited set of information (maybe restrict to what the functions print currently)~~

Add platform name to be printed by `print_device_info`.

**Comment by diptorupd** [comment]
@1e-to I think printing each info and aspect will be too much noise and too much work. I updated the task to just one minor change.

**Comment by diptorupd** [comment]
Addressed in #409.
