### ISSUE TITLE
Unit tests should be added for all publicly exposed APIs

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/dpctl#3]
For all interfaces, dppl and dppl.ocldrv we should add unit tests to make sure the functions are behaving correctly.

**Comment by PokhodenkoSA** [comment]
I think we should use test coverage or do manual collecting of not tested APIs.

**Comment by diptorupd** [comment]
I am closing this issue as it is too broad and our test suites have improved significantly since the ticket was opened. We should raise tickets for specific functions based on coverage analysis.
