### ISSUE TITLE
Rename PyDPPL to dpCtl

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#31]
pyDPPL is to be renamed to `dpCtl` and the Python module is to be renamed to `dpctl`.

It is necessary to make it safer:
1. add new API
2. reimplement the old API via new API
3. mark old API as deprecated
4. remove old API in the next release

Related to #123.

**Comment by PokhodenkoSA** [comment]
Plan:
- [ ] Rename module `dppl` to `dpctl`
- [ ] Rename package from `pydppl` to `dpctl`
- [ ] Rename GitHub repo from `IntelPython/pydppl` to `IntelPython/dpCtl`

**Comment by diptorupd** [comment]
@PokhodenkoSA Can we get this in for 0.5.0? We need to let downstream projects like daal4py and dpnp be aware of these changes.

**Comment by PokhodenkoSA** [comment]
> Can we get this in for 0.5.0?

Yes. @1e-to do the work for renaming.

**Comment by diptorupd** [comment]
All dpctl changes are complete (#201). The Numba-dppy changes are being tracked in numba-dppy PR#42. I will close the issue once the numba-dppy PR is merged.

**Comment by diptorupd** [comment]
All changes have been completed.
