### ISSUE TITLE
Allow Sycl queue creation with an async_handler and supported SYCL properties

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#312]
It should be possible to create SYCL queues from `dpctl` while specifying supported properties (`IN_ORDER`, `ENABLE_PROFILING`) to the queue constructor.

Asynchronous errors should be handled and reported back to Python users.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Should we close this ticket? Or do we need more test cases and examples?

**Comment by oleksandr-pavlyk** [comment]
Dpctl async handler is being set during queue/context construction. It id not user modifiable.

Properties of queue can be set. Examples showing that were added.

Closing this issue is appropriate.
