### ISSUE TITLE
Release dpctl 0.7.0

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#325]
@PokhodenkoSA a significant amount of features have been now merged into master to warrant a new release. I am collecting the pending tickets that we should complete. More may come as @1e-to 's sub-device work nears completion. After that is done let us release 0.7.0.

- [x] #324
- [x] #331
- [x] #327 
- [x] #326
- [x] #308
- [x] Update changelog and release notes.
- [x] Update API docs
- [x] Update examples

**Comment by oleksandr-pavlyk** [comment]
Support for capsules should also be part of 0.7

**Comment by diptorupd** [comment]
0.7.0 is now released.
