### ISSUE TITLE
Project naming convention

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#330]
We can see several names in different cases:
- `dpctl` (package name)
- `dpCtl` (documentation)
- `DPCTL` (C++ code)

I propose to make it simple and use `dpctl` in all places.

**Comment by diptorupd** [comment]
Standardizing on `dpctl` is fine. Let us follow the GTK naming convention: All C API function names will use a _`dpctl_`_ prefix followed by a symbol name and words separated with `_`, _e.g._ `dpctl_device_is_host`. Structs should use _`Dpctl`_ prefix and use `CamelCase` naming style. Macros will use _`DPCTL_`_ prefix and use underscore separated words in all caps.

The problem might be we might end up with very long names.

**Comment by PokhodenkoSA** [comment]
I propose to be close to SYCL API style.

**Comment by oleksandr-pavlyk** [comment]
This has been adequately resolved. Voting to close.

**Comment by diptorupd** [comment]
The issue of C++ function names is still to be resolved.

**Comment by diptorupd** [comment]
The name has been standardized everywhere with the exception of `libsyclinterface`. In `libsyclinterface`, the `DPCTL` prefix continues to be used and changing that buys us very little. I will document the naming convention in our future programmer's manual.
