### ISSUE TITLE
Run gtest on CI

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#333]
@PokhodenkoSA how can the C API gtests be run on Windows? I am using the `dbg_build.bat` script in this PR. If I do `ninja check` I can successfully build the tests, but after that get an error. Most likely the issue is the the `DPCTLSyclInterface.dll` is not found. It will be good to apply a fix if it is a small one and have the C API tests run on Windows and CI.

_Originally posted by @diptorupd in https://github.com/IntelPython/dpctl/issues/319#issuecomment-805340266_

**Comment by PokhodenkoSA** [comment]
Linux CI runs gtest when CODE_COVERAGE is enabled.

**Comment by diptorupd** [comment]
@vlad-perevezentsev I made an initial attempt in #355

**Comment by oleksandr-pavlyk** [comment]
> @vlad-perevezentsev I made an initial attempt in #355 and @1e-to started the work last year in #109

For #355 to work in our CI we need `gtest` package available on tools conda channel

**Comment by oleksandr-pavlyk** [comment]
With changes in #425, backend dpctl-capi test suite is run with `python setup.py develop --coverage=1`.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk  We do run gtest in out github CI, fixing the problems in TeamCity is another ball game that is not related to our code. I am inclined to close the issue.

**Comment by diptorupd** [comment]
closing the issues. We can reopen if there is a specific need for Windows CI or internal testing in the future.
