### ISSUE TITLE
Variable `non_existent_device_num` but passed to `DPPLGetQueue()`

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#37]
https://github.com/IntelPython/pydppl/blob/78aba38fdaa62ca5a074ecfecee4529f4760f6fb/backends/tests/test_sycl_queue_manager.cpp#L60

I think variable name should be `non_existent_queue_num`.
Do I miss any idea here? Why is it named `...device...`?

**Comment by diptorupd** [comment]
The idea is that if the queue does not exist as the specified device is not found.
