### ISSUE TITLE
Convert `dpctl.get_current_queue().sycl_device.name` to a property

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#381]
Perhaps it should be `dpctl.get_current_queue().sycl_device.name` to simplify?

_Originally posted by @oleksandr-pavlyk in https://github.com/IntelPython/dpctl/pull/378#discussion_r611761410_

**Comment by oleksandr-pavlyk** [comment]
The comment intended to say that `dpctl.get_current_queue().sycl_device.name` is simpler than ``dpctl.get_current_queue().sycl_device.get_device_name()``.

The question though is, should we provide access to certain device-specific properties to the queue directly.

Examples of these would be 

```python
import dpctl
q = dpctl.SyclQueue()
q.backend # should map to q.sycl_device.backend
q.device_name # should map to q.sycl_device.name
q.driver_version # should map to q.sycl_device.driver_version
q.print_device_info # should map to q.sycl_device.print_device_info
```

These are easy to implement, and would improve usability.
