### ISSUE TITLE
Add a requirements.txt to repo.

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#398]
Let us provide the specific versions of each of these dependencies if not a range of versions

_Originally posted by @reazulhoque in https://github.com/IntelPython/dpctl/pull/397#discussion_r616170471_

**Comment by diptorupd** [comment]
Also update quick start guide once requirements.txt is added.

**Comment by oleksandr-pavlyk** [comment]
The requirements.txt was added in #540 

Specific versions were not pinned though.
