### ISSUE TITLE
USM malloc_device based Device array container

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#46]
`dppl.ocldrv` has a container called DeviceArray that is based on OpenCL `cl_mem` buffer. We need a equivalent one in `dppl` based on malloc_device.

1. Create _arrays.pyx and create a `DeviceArray` class inside it.
2. Look at `ocldev.DeviceArray` and [cupy.ndarray](https://docs.cupy.dev/en/stable/reference/generated/cupy.ndarray.html) for ideas. The following attributes should be provided by the new array. 
- base (None or dppl.DeviceArray) – Base array from which this array is created as a view.
- data (malloc_device MemoryPointer) – Pointer to the array content head.
- dtype (numpy.dtype) – Dtype object of element type.
- size (int) – Number of elements this array holds.

Unlike `cupy.ndarray` at this time no need to have member functions beyond getters/setters for the above attributes. **We can reevaluate later.**

3. Does the new `DeviceArray` need to store a reference to the `numpy.ndarray` from which it was created? 
We were doing this in `ocldrv.DeviceArray` and this feature might be used in Numba, but I do not think we should keep doing it. We have received multiple user feedback that the feature is not very intuitive when copying data to/from an `ocldrv.DeviceArray'. **Let's evaluate the design.**

**Data Copy Functions**

`dppl.ocldrv` has two data copy functions `copy_array_to_device` and `copy_array_from_device` in DeviceEnv class. The design is not very good. For `dppl.DeviceArray` we should have a similar interface as [cupy conversion functions](https://docs.cupy.dev/en/stable/reference/ndarray.html#conversion-to-from-numpy-arrays).

**Memory module**

Expose memcpy functions inside the memory module.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Since we are planning to have `dpctl.dptensor`, eventually a USM device-based tensor should be part of the sub-module. Right?  If so, we can use this ticket to track the work.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Is this ticket relevant any more as we move to `usm_array`?

**Comment by oleksandr-pavlyk** [comment]
`dpctl.tensor.usm_ndarray` provides an ability to create USM-device backed array.
