### ISSUE TITLE
Implement an analog of cuda stream functions

### ISSUE THREAD

**Issue by 1e-to** [IntelPython/dpctl#498]
Queue in SYCL uses when we migrate from CUDA. For the following functions, you need to implement analogues

- [x] numba.cuda.stream (queue)
- [ ] numba.cuda.default_stream
- [ ] numba.cuda.legacy_default_stream 
- [ ] numba.cuda.per_thread_default_stream 
- [ ] numba.cuda.external_stream 
- [ ] numba.cuda.cudadrv.driver.Stream 
- [ ] auto_synchronize 
- [x] synchronize (event)

**Comment by diptorupd** [comment]
Closing the issue as it is not relevant to current dpctl queue management API. The `numba.cuda` stream API is very specific to CUDA runtime and we will not have equivalency in dpctl.

CC
@oleksandr-pavlyk
