### ISSUE TITLE
Set up a public CI for dpctl using Intel DevCloud

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#501]
Explore using Intel Devcloud's GPU nodes to set up a public CI.

**Initial steps to try build dpctl from source on DevCloud.**
- [x] **Step1.** Test Devcloud oneAPI setup: Log in to Intel DevCloud. Submit a job on a Gen9 node and print `dpcpp --version`.
- [x] **Step2.** Build dpctl on Devcloud: Create an interactive job on a Gen9 node of Devcloud and build dpctl from source using conda.
- [x] **Step3.A** Create a script to submit a batch job to achieve Step 2. The output of the batch job should be a conda channel.
- [x] **Step3.B** Submit the batch job and wait for completion.
- [x] **Step4.** Create a script that will run on a login node to keep checking if the batch job has completed.

**Automate build of dpctl (Steps 1-4) via a Github action.**

- [ ] **Step5.** Add a new Github action that will ssh to Intel DevCloud possibly using https://github.com/appleboy/ssh-action. 
- [ ] **Step6.** Run Steps 3 via the Github action and the finish the Github action job. Wait for job to complete and see if conda channel is created.

**Retrieve conda channel from Devcloud and publish on Github**
_TODO._

**Comment by ogrisel** [comment]
Out of curiosity, why not directly use GitHub Actions to build dpctl and run its tests? It should be enough at least to test against CPU devices, right?

**Comment by diptorupd** [comment]
@ogrisel  We are already doing that. We want to make it possible to regularly publicly test dpctl with Level zero driver on Intel GPU devices. We do run L0 GPU tests in our internal CI. The point of having a public CI was to help external collaborators, as run logs for our internal CI are not available outside our network.

**Comment by ogrisel** [comment]
That would be great indeed, thanks for the clarification.

**Comment by diptorupd** [comment]
It was deemed infeasible to set up a CI this way. In any case Devcloud is now a paid service.
