### ISSUE TITLE
Add support for SYCL 2020 kernel bundles and remove wrappers for sycl::program

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#502]
SYCL 2020 spec does not have a class called `program` instead it introduces the `kernel_bundle` class. 

- [x] Add C API for kernel bundle
- [ ] Deprecate or remove `DPCTLProgram_*` functions.

**Comment by oleksandr-pavlyk** [comment]
The use of `sycl::program` has been upgraded to use `sycl::kernel_bundle<sycl::bundle_state::executable>` in #845, but SyclInterface binding remained the same. Ready to close.
