### ISSUE TITLE
MemoryUSMxxx classes should provide a factory function to copy data between incompatible device

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#54]
Moved here as part of #27. Was not implemented there.
Implementation of this issue requires wrapping of `queue::memcpy()`.

**Comment by oleksandr-pavlyk** [comment]
It  has been implemented in #152, see method `.copy_from_device`. `MemoryUSMShared_instance.copy_from_device( MemoryUSMDevice_instance)` will do that.
