### ISSUE TITLE
dpm.as_usm_memory(X[i]) returns unexpected value

### ISSUE THREAD

**Issue by densmirn** [IntelPython/dpctl#583]
Reproducer:
```python
import dpctl
print(dpctl.__version__)
import dpctl.tensor as dpt
import dpctl.memory as dpm
X = dpt.usm_ndarray(10, dtype="|f8")
Y = np.arange(X.size, dtype=X.dtype)
X.usm_data.copy_from_host(Y.view("|u1"))
print("X =", dpm.as_usm_memory(X).copy_to_host().view(X.dtype))
print("X[0] =", dpm.as_usm_memory(X[0]).copy_to_host().view(X.dtype))
print("X[1] =", dpm.as_usm_memory(X[1]).copy_to_host().view(X.dtype))
print("X[2] =", dpm.as_usm_memory(X[2]).copy_to_host().view(X.dtype))
```
Output:
```
0.10.0dev0+44.gb60ce2a.dirty
X = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
X[0] = [0.]
X[1] = [2.]
X[2] = [4.]
```

**Comment by oleksandr-pavlyk** [comment]
Thanks for the report @densmirn 

The sycl USM array interface produced by the slice gives the actual memory address, and also sets `offset` which specifies the location of this memory address from the start of the underlying allocation. 

The `dpm.as_memory` interprets `offset` as saying start at this additional displacement relative to the provided pointer. The fix should not be complicated, but I need to trace through the code to understand what is the correct way to handle `offset`.
