### ISSUE TITLE
Importing dppl fails when no CPU OpenCL driver is found on the system

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#6]
Importing dppl should not fail if a GPU OpenCL driver exists but no CPU driver is found.

**Comment by diptorupd** [comment]
@reazulhoque Can you please investigate this issue? It may have gotten fixed in all the recent changes we have made to dppl. The issue is to cleanly handle the case when someone tried `import dppl` but the system has either no OpenCL/Level-0 drivers or it only has a GPU driver and no CPU driver.

**Comment by diptorupd** [comment]
@PokhodenkoSA This one may already be fixed. If I recall correctly the issue was thet module will not load if no CPU device existed. But, we have been running without issue on CI where there is no CPU present.

Can be closed?

**Comment by PokhodenkoSA** [comment]
Correct. Can be closed.
