### ISSUE TITLE
CMake compiler check fail with Python 3.9 and intel channel

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#600]
I had to disable intel channel for building because of CMake compiler check fail.
It should be investigated.

_Originally posted by @PokhodenkoSA in https://github.com/IntelPython/dpctl/issues/599#issuecomment-929023810_

**Comment by oleksandr-pavlyk** [comment]
I did not have any problems building `dpctl`  for Python 3.9 using system cmake:

```
(py39) [13:31:36 ansatnuc04 dpctl]$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by PokhodenkoSA** [comment]
Investigation results: https://github.com/IntelPython/dpctl/pull/599#issuecomment-930280313
