### ISSUE TITLE
Level Zero module creation fails

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#609]
Encountering the following error with dpctl master anddpcpp 2021.4

```
Note: Google Test filter = TestQueueSubmit.CheckSubmitRange_saxpy
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TestQueueSubmit
[ RUN      ] TestQueueSubmit.CheckSubmitRange_saxpy
    Name            Intel(R) UHD Graphics 630 [0x3e98]
    Driver version  1.2.20889
    Vendor          Intel(R) Corporation
    Profile         FULL_PROFILE
    Filter string   level_zero:gpu:0
The level zero loader dynamic library could not be opened.
ZeModuleCreateFn is invalid.

```

**Comment by diptorupd** [comment]
@oleksandr-pavlyk I seem to not have `libzeloader.so` on my system. I do have `libze_loader.so.1` and `libze_loader.so.1.4.1`. Any idea what package I am missing?

**Comment by oleksandr-pavlyk** [comment]
I encountered the same issue with OS LLVM/SYCL, see #603 

I guess the library had been renamed.

**Comment by diptorupd** [comment]
or the `libze-loader` Ubuntu package is corrupted. I built the library by hand and do see `libze_loader.so`.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk I have a temporary workaround: build and install `libze_loader` by hand (https://github.com/oneapi-src/level-zero) and then add the library to the `LD_LIBRARY_PATH`.

The [compute runtime page](https://github.com/intel/compute-runtime/blob/master/level_zero/doc/DISTRIBUTIONS.md) suggests installing `apt install libze-loader libze-intel-gpu` which is what I have on my system. However, the [oneapi dgpu installation guide](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html) suggests other packages:

```
sudo apt-get update
sudo apt-get install \
  intel-opencl-icd \
  intel-level-zero-gpu level-zero \
  intel-media-va-driver-non-free libmfx1
```
I cannot even install the `intel-level-zero-gpu` and `level-zero` packages without first having to install `libigc1` and `libigdfcl1` by hand.

@PokhodenkoSA @reazulhoque do you know how level zero loader is installed in our TeamCity systems? I wonder why we are not running into the issue in our internal CI. Maybe the drivers are not updated in a while?

**Comment by oleksandr-pavlyk** [comment]
I always uninstall all drivers, and then reinstall them using one command from install Intel GPU drivers page for apt on Ubuntu 20.04

I did that on the linux CI machine 2 weeks back.

**Comment by PokhodenkoSA** [comment]
@diptorupd 
I faced this issue https://github.com/IntelPython/numba-dppy/issues/530.
`libze_loader.so` is in apt package `level-zero-dev`.

**Comment by PokhodenkoSA** [comment]
I think dpctl should load dynamically `libze_loader.so.1` instead of `libze_loader.so`.

**Comment by PokhodenkoSA** [comment]
For me I find this documentation incorrect: [compute runtime page](https://github.com/intel/compute-runtime/blob/master/level_zero/doc/DISTRIBUTIONS.md).
For rolling back I had to remove ppa: `add-apt-repository --remove ppa:intel-opencl/intel-opencl`.
After that I use instructions from:  [oneapi dgpu installation guide](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html).

**Comment by diptorupd** [comment]
> @diptorupd I faced this issue [IntelPython/numba-dppy#530](https://github.com/IntelPython/numba-dppy/issues/530). `libze_loader.so` is in apt package `level-zero-dev`.

Yes, that worked for me.

**Comment by oleksandr-pavlyk** [comment]
> I think dpctl should load dynamically `libze_loader.so.1` instead of `libze_loader.so`.

We definitely should align with whatever `${CONDA_PREFIX}/lib/libpi_level_zero.so}` links to:

```
(idp_2021.4) [15:31:52 ansatnuc04 dpctl-capi]$ ldd /opt/intel/oneapi/intelpython/python3.7/lib/libpi_level_zero.so | grep libze_
        libze_loader.so.1 => /lib/x86_64-linux-gnu/libze_loader.so.1 (0x00007f450870e000)
```

We should infer this filename at the build time, and inject this filename in the source before starting the build. 

Perhaps make it a part of `dpctl-capi/Config/dpctl_config.h.in`.

**Comment by diptorupd** [comment]
closing as installing `level-zero-dev` solves the problem.
