### ISSUE TITLE
dpctl needs to provide get_include()

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [IntelPython/dpctl#64]
When building Cython native application that builds on `dpctl`, `include_dir` option of the `Extension` need to point to `dpctl/backend/include` to pick up `dpctl` utilities.

`dpctl` must provide a function that returns the location of that folder in the installation, very much like what `numpy.get_include()`  does. See: https://numpy.org/devdocs/reference/generated/numpy.get_include.html

**Comment by oleksandr-pavlyk** [comment]
This also means that these header files must be in the installation layout.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Since #69 is merged, can this be closed?

**Comment by oleksandr-pavlyk** [comment]
Yes, this is implemented
