### ISSUE TITLE
PyPI dpctl project description needs changes

### ISSUE THREAD

**Issue by samaid** [IntelPython/dpctl#656]
For project description please use Intro text I suggested for README.MD. Remove everything else from there, and instead provide the link to github.io documentation

**Comment by diptorupd** [comment]
@samaid @oleksandr-pavlyk We have refactored the README. Can you review the latest README and see if the description is better?

**Comment by oleksandr-pavlyk** [comment]
Closing due to vague issue description, and lack of activity.
