### ISSUE TITLE
Remove ghost branches

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#668]
@oleksandr-pavlyk We have too many branches lying around that no one maintains. Can we do a pass over the dead branches and clean them up?

**Comment by oleksandr-pavlyk** [comment]
The branch [`gh408-capsule`](https://github.com/IntelPython/dpctl/tree/gh408-capsule) is mine and relates to #408, and exists as evidence for why it is not much better than the existing behavior. 

It appears that the branch  [`spokhode/ci/gpu`](https://github.com/IntelPython/dpctl/tree/spokhode/ci/gpu`) is abandoned. @PokhodenkoSA please delete is so.

The branch [`usm_shared_array_inplace`](https://github.com/IntelPython/dpctl/tree/usm_shared_array_inplace) is likely also dead. @DrTodd13 please delete if so.

Branch [`beta/2021`](https://github.com/IntelPython/dpctl/tree/beta/2021) should just be deleted. 

The branch [`gtest`](https://github.com/IntelPython/dpctl/tree/gtest) is very old, has no PR associated with it. @PokhodenkoSA please delete.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk Thanks for checking. Now only https://github.com/IntelPython/dpctl/tree/usm_shared_array_inplace is left.

**Comment by oleksandr-pavlyk** [comment]
The `usm_shared_array_inplace` is not salvageable, there are conflicts from attempting to merge to master. 

I would therefore vote to delete this branch, but think @DrTodd13 should be given a chance to tell us otherwise.
