### ISSUE TITLE
Runtime message when calling dpctl.tensor.asarray: No parent for device because it is not a subdevice -33

### ISSUE THREAD

**Issue by densmirn** [IntelPython/dpctl#714]
Reproducer:
```python
In [1]: import dpctl.tensor as dpt
In [2]: a = dpt.asarray([0,1,2,3,4])
In [5]: dpnp.asarray(a)
No parent for device because it is not a subdevice -33 (CL_INVALID_DEVICE) in DPCTLDevice_GetParentDevice at /localdisk/work/denissmi/dpctl/libsyclinterface/source/dpctl_sycl_device_interface.cpp:540
```
dpctl version:
```python
In [6]: import dpctl
In [7]: dpctl.__version__
Out[19]: '0.12.0dev1+71.g439c2f4d'
```

**Comment by oleksandr-pavlyk** [comment]
@densmirn Please check the value of `DPCTL_VERBOSITY` environment variable in your environment. 

@vlad-perevezentsev Could you look into why the message is being printed?

**Comment by densmirn** [comment]
DPCTL_VERBOSITY is empty in my environment.
```
(dpctl-build) denissmi@ansatnuc06:/localdisk/work/denissmi/dpnp_fork$ echo DPCTL_VERBOSITY=$DPCTL_VERBOSITY
DPCTL_VERBOSITY=
```

**Comment by vlad-perevezentsev** [comment]
@oleksandr-pavlyk The error output condition is incorrect in `dpctl_error_handlers.cpp`
All error types are output with an unassigned `DPCTL_VERBOSITY`. It will be fixed.
@densmirn Thanks for the report. 
Temporary solution: You can set the `DPCTL_VERBOSITY=warning` to not see this message.

**Comment by oleksandr-pavlyk** [comment]
BTW, I can not reproduce the observed behavior.

**Comment by oleksandr-pavlyk** [comment]
I see, in `get_requested_level`, the default initialization for `requested_level` should be `static_cast<int>(error_level::last) + 1`.

where `error_level::last` should be added to 256, or something.

**Comment by vlad-perevezentsev** [comment]
@oleksandr-pavlyk Why can't we just replace `<=` with `>=` in `error_handler` conditions?

**Comment by oleksandr-pavlyk** [comment]
@vlad-perevezentsev Yes, that works. In that case please rename `get_requested_level` to `requested_verbosity_level` for better readability.
