### ISSUE TITLE
test_windows job of conda-packages workflow fails

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [IntelPython/dpctl#734]
The test_windows job fails because in oneAPI DPC++ 2022.0 the opencl loader no longer responds to `OCL_ICD_FILENAMES` environment variable, and the `dpctl` only sees the host device (as seen due to changes in #733 ).

Instead of relying on the environment variable I tried to install opencl CPU driver (https://github.com/intel/llvm/releases/download/2021-WW50/win-oclcpuexp-2021.13.11.0.23_rel.zip) into job environment (this hangs due to errors in installation script).

I tried to use `regsrv32`  on `"libintelocl.so"`. This did not work properly (only host devices was being detected) since one likely needs to register other shared objects, but I am not sure which.

This issue is a call for help in solving the problem.

**Comment by PokhodenkoSA** [comment]
Fast fix is to pin previous version.

**Comment by oleksandr-pavlyk** [comment]
Not desirable. It is best if we find a proper fix. I am sure DPC++ team has solved this issue somehow.

**Comment by PokhodenkoSA** [comment]
It will give time while they will fix our ticket.

**Comment by oleksandr-pavlyk** [comment]
Fixed with #733
