### ISSUE TITLE
Stack variables in cython is being resued when multiple scalar arguments are being passed

### ISSUE THREAD

**Issue by reazulhoque** [IntelPython/dpctl#77]
In queue.submit() in sycl_core.pyx, we declare variables of diffferent types once and then we try to assign the address of that variable to pass the the submit function in C/++. This results in wrong behavior when we have same type of multiple scalar arguments.

**Comment by diptorupd** [comment]
Latest /feature/program_interface should have a fix for the issue. Can you please retest?

**Comment by reazulhoque** [comment]
Retested, seems solved.
