### ISSUE TITLE
return No device of requested type available in ssh.

### ISSUE THREAD

**Issue by WanBenLe** [IntelPython/dpctl#782]
I use a docker container with dpctl on the server to configure SSH and try out pycharm connections from other computers on the intranet, docker uses

`docker run -p 22:8080 ... ...and others...`
 An error is reported when running the following code in pycharm(windows 10):
`import dpctl`
`print(dpctl.select_default_device())`

#
Connected to pydev debugger (build 212.5457.59)
No device of requested type available. Please check https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-dpcpp-system-requirements.html -1 (CL_DEVICE_NOT_FOUND)
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/datalab/ben/home/datalab/ben/testgogogo.py", line 12, in <module>
    print(dpctl.select_default_device())
  File "dpctl/_sycl_device_factory.pyx", line 343, in dpctl._sycl_device_factory.select_default_device
python-BaseException
  File "dpctl/_sycl_device_factory.pyx", line 358, in dpctl._sycl_device_factory.select_default_device
ValueError: Device unavailable.
#

The following is the result of a successful run in the server(Ubuntu 16.04):
`python`
`import dpctl`
`device = dpctl.select_default_device()`
`device.print_device_info()`

#
Python 3.8.11 (default, Sep 14 2021, 14:36:04)
[GCC 9.3.0] :: Intel Corporation on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
Name            Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz
Driver version  2021.13.11.0.23_160000
Vendor          Intel(R) Corporation
Profile         FULL_PROFILE
Filter string   opencl:cpu:0
#

I would like to ask if dpctl incorrectly identifies the device when using a python with SSH connection?

**Comment by oleksandr-pavlyk** [comment]
Since no response has been provided, closing. Please feel free to reopen, or file a new ticket should you need further assistance.
