### ISSUE TITLE
Intel DevCloud - AttributeError: module 'dpctl.tensor' has no attribute 'arange'

### ISSUE THREAD

**Issue by olutosinbanjo** [IntelPython/dpctl#856]
Hi team,

I am testing dpctl and dpnp modules on the Intel DevCloud. 

A test for the `dpctl.tensor` module shows that it has no `arange()` attribute;

see example - this python script : 

$ cat test.py

```python3
import dpctl
import dpnp as np
import dpctl.tensor as dpt

def test_np_array():
    x = np.array([1,2,3])
    s = np.sum(x)
    print("Testing np.array(): ")
    print("The sum of np array: ", s, '\n')

def test_np_arange():
    r = np.arange(1, 4)
    q = np.sum(r)
    print("Testing np.arange(): ")
    print("The sum of np array: ", q, '\n')

def test_dpt_asarray():
    w = [1, 2, 3]
    e = dpt.asarray(w)
    f = np.sum(e)
    print("Testing dpt.asarray(): ")
    print("The sum of dpt asarray: ", f, '\n')

def test_dpt_arange():
    y = dpt.arange(1, 4)
    t = np.sum(y)
    print("Testing dpt.arange(): ")
    print("The sum of dpt array: ", t, '\n')

def main():
    with dpctl.device_context("opencl:gpu"):
        test_np_array()
        test_np_arange()
        test_dpt_asarray()
        test_dpt_arange()

if __name__ == "__main__":
    main()
```

The following execution result for `test.py` shows that the `dpctl.tensor` module has no `arange()` attribute :

$ python3 test.py

```
Testing np.array():
The sum of np array:  6

Testing np.arange():
The sum of np array:  6

Testing dpt.asarray():
The sum of dpt asarray:  6

Traceback (most recent call last):
  File "/home/u*****/dpnp/MY_PYTHON_PROJECTS/test.py", line 38, in <module>
    main()
  File "/home/u*****/dpnp/MY_PYTHON_PROJECTS/test.py", line 35, in main
    test_dpt_arange()
  File "/home/u*****/dpnp/MY_PYTHON_PROJECTS/test.py", line 25, in test_dpt_arange
    y = dpt.arange(1, 4)
```

I have also tested with an example from the examples folder in the dpctl repository - `sycl_timer.py`. 

$ python3 sycl_timer.py

```
Traceback (most recent call last):
  File "/home/u*****/dpnp/MY_PYTHON_PROJECTS/sycl_timer.py", line 36, in <module>
    a = dpt.reshape(dpt.arange(n * n, dtype=np.float32, sycl_queue=q), (n, n))
AttributeError: module 'dpctl.tensor' has no attribute 'arange'
```

Could you kindly look into this ? Thank you.

**Comment by oleksandr-pavlyk** [comment]
@olutosinbanjo Please include what version of `dpctl` you are using. Please be advised that Intel Distribution for Python included in oneAPI 2022.2 installation available on Dev-Cloud ships with dpctl 0.12.0.

The `dpctl.tensor.arange` was [added later](https://github.com/IntelPython/dpctl/pull/814/commits/94380f6ea83d04ba662f618ebb3f889df802fbff).

If you are working from a terminal, rather than from Jupyter Notebook, you can create conda environment with the build from the main branch like so:

```bash
$ conda create -n dev-dpctl \
     -c dppy/label/dev  -c /opt/intel/oneapi/conda_channel \
     --override-channels --yes \
     python=3.9 dpctl=0.13.* dpnp pkgs/main::ipython 
```

Now:

```bash
$ conda activate dev-dpctl
$ python test.py   # arange is available now
```

However, if you are working from a login node, `opencl:gpu` device is not going to be available. 

The offload control should be specified using compute-follows-data programming model. Please refer to our [virtual poster](https://intelpython.github.io/oneAPI-for-SciPy/details/programming_model/) at [SciPy'22](https://www.scipy2022.scipy.org/posters) for more details.

Specifically, you no longer need to specify the offload target using `with dpctl.device_context` to work with `dpnp`.

After changing the definition of `main` routine to 

```python
def main():
    test_np_array()
    test_np_arange()
    test_dpt_asarray()
    test_dpt_arange()
```

I got:

```
(dev-dpctl) u******@s001-n011:~$ python test.py 
Testing np.array(): 
The sum of np array:  6 

Testing np.arange(): 
The sum of np array:  6 

Testing dpt.asarray(): 
The sum of dpt asarray:  6 

Testing dpt.arange(): 
The sum of dpt array:  6 
```

Hope this helps.

**Comment by olutosinbanjo** [comment]
@oleksandr-pavlyk,

Thank you. Your suggestions helped.

First attempt:

```
conda create -n dev-dpctl \
     -c dppy/label/dev  -c /opt/intel/oneapi/conda_channel \
     --override-channels --yes \
     python=3.9 dpctl=0.13.* dpnp pkgs/main::ipython 
```

```
$ s-n***: conda activate dev-dpctl
$ (dev-dpctl) s-n***: python3 test.py
```

Result: 
```
Traceback (most recent call last):
  File "/home/u*****/dpnp/MY_PYTHON_PROJECTS/test.py", line 2, in <module>
    import dpnp as np
  File "/home/u*****/.conda/envs/dev-dpctl/lib/python3.9/site-packages/dpnp/__init__.py", line 39, in <module>
    from dpnp.dpnp_iface import *
  File "/home/u*****/.conda/envs/dev-dpctl/lib/python3.9/site-packages/dpnp/dpnp_iface.py", line 51, in <module>
    from dpnp.dpnp_algo import *
  File "/home/u*****/.conda/envs/dev-dpctl/lib/python3.9/site-packages/dpnp/dpnp_algo/__init__.py", line 27, in <module>
    from dpnp.dpnp_algo.dpnp_algo import *
ImportError: libmkl_sycl.so.2: failed to map segment from shared object
```

Second attempt:
```
conda create -n dev-dpnp -c dppy/label/dev python=3.9 dpnp dpctl
```

```
$ s-n***: conda activate dev-dpnp
$ (dev-dpnp) s-n***: python3 test.py
```

Result:

```
Testing np.array():
The sum of np array:  6

Testing np.arange():
The sum of np array:  6

Testing dpt.asarray():
The sum of dpt asarray:  6

Testing dpt.arange():
The sum of dpt array:  6
```

Third attempt :

```
conda create -n dev-dpctl \
> -c dppy/label/dev -c /opt/intel/oneapi/conda_channel \
> --override-channels --yes \
> python=3.9 dpctl=0.13.* dpnp pkgs/main::ipython
```

```
$ s-n***: conda activate dev-dpctl
$ (dev-dpctl) s-n***: python3 test.py
````

Result:
```
Testing np.array():
The sum of np array:  6

Testing np.arange():
The sum of np array:  6

Testing dpt.asarray():
The sum of dpt asarray:  6

Testing dpt.arange():
The sum of dpt array:  6
```

what I learnt :

1. dpctl.tensor.arange() is available in dpctl version 0.13.*

2. if conda environment is for example -
```
conda create -y -n dev-dpctl python=3.9
conda install -c intel dpnp 
conda install -c dppy/label/dev dpctl
```

```
$ s-n***: conda activate dev-dpctl
$ (dev-dpctl) s-n***: python3 test.py
````

Result:
```
Traceback (most recent call last):
  File "/home/u*****/dpnp/MY_PYTHON_PROJECTS/test.py", line 1, in <module>
    import dpnp as np
  File "/home/u*****/dpnp/dpnp/__init__.py", line 39, in <module>
    from dpnp.dpnp_iface import *
  File "/home/u*****/dpnp/dpnp/dpnp_iface.py", line 51, in <module>
    from dpnp.dpnp_algo import *
  File "/home/u*****/dpnp/dpnp/dpnp_algo/__init__.py", line 27, in <module>
    from dpnp.dpnp_algo.dpnp_algo import *
  File "dpnp/dpnp_algo/dpnp_algo.pyx", line 1, in init dpnp.dpnp_algo.dpnp_algo
ValueError: dpctl._sycl_event._SyclEvent size changed, may indicate binary incompatibility. Expected 32 from C header, got 24 from PyObject
```

Reason: 
```
-c intel dpnp is incompatible with -c dppy/label/dev dpctl

(dpnp package from channel intel is incompatible with dpctl package from channel dppy/label/dev)
```

Use instead:

```
-c dppy/label/dev dpnp dpctl

(install dpnp and dpctl packages from dppy/label/dev channel)
```

One question: 

Any idea why I got an Import error on first attempt (ImportError: libmkl_sycl.so.2: failed to map segment from shared object) ?

Thanks.

**Comment by oleksandr-pavlyk** [comment]
> One question: Any idea why I got an Import error on first attempt (ImportError: libmkl_sycl.so.2: failed to map segment from shared object) ?

I just tried recreating the first environment and reproducing the crash and it worked for me out of the box. If you can reliably reproduce the problem, please share output of `conda list -n dev-dpctl --explicit` with `dev-dpctl` being the environment where the `ImportError` can be reproduced. 

Generally this error means that one of native extensions implicitly used in your script (an extension in `dpnp` to be specific) and during Python's attempt to load the extension the attempt to load its dependent dynamic library failed. The precise reason for the failure is not reported in the error, so I would need to exactly replicate your environment to find out more.

**Comment by olutosinbanjo** [comment]
Oh, I realized that it was my mistake. On my first attempt I was working on the login node rather than a compute node on the devcloud.

So, the Import error  should occur if you:

```
$ ssh devcloud
$ login-node : conda activate dev-dpctl
$ (dev-dpctl) login-node : python3 test.py
```
Thanks again for your help.
