### ISSUE TITLE
Request for additonal attribute `preferred_work_group_size_multiple`

### ISSUE THREAD

**Issue by fcharras** [IntelPython/dpctl#886]
[`dpctl.SyclDevice`](https://documen.tician.de/pyopencl/runtime_const.html#pyopencl.device_info.PREFERRED_WORK_GROUP_SIZE_MULTIPLE) exposes a number of useful attributes when scheduling kernels, but `preferred_work_group_size_multiple` seems to be an important information (used when choosing kernel local size) that is missing.

It is available with [clinfo](https://github.com/Oblomov/clinfo):

```
> clinfo
...
Device Name                                     Intel(R) UHD Graphics [0x9a60]
...
Device Type                                     GPU
...
Max work group size                             512
Preferred work group size multiple              64
...
```  

or exposed in [pyopencl](https://documen.tician.de/pyopencl/runtime_const.html#pyopencl.device_info.PREFERRED_WORK_GROUP_SIZE_MULTIPLE)

**Comment by fcharras** [comment]
(global and local cache sizes would be a useful addition too)

**Comment by oleksandr-pavlyk** [comment]
The `preferred_work_groups_size_multiple` is exposed in SYCL as a device-specific information about a kernel, see [Table 136](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.kernel.devicespecificinfo) in the SYCL 2020 spec rev. 5.

Querying it requires a kernel, which can only be extract from a kernel bundle in the executable state.

**Comment by oleksandr-pavlyk** [comment]
Device object could definitely expose 

``sycl::info::device::global_mem_cache_type`` (can be `none`, `read_only`, `read_write`), ``sycl::info::device::global_mem_cache_line_size`` and ``sycl::info::device::global_mem_cache_size``. 

There does not seem to be any descriptor to query local cache size. Only the `local_mem_size` which is already exposed as `dpctl.SyclDevice.local_mem_size` property.

@fcharras Could you please clarify what you mean by "local cache sizes" and perhaps refer to it in `clinfo` output?

**Comment by fcharras** [comment]
> The `preferred_work_groups_size_multiple` is exposed in SYCL as a device-specific information about a kernel, see [Table 136](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.kernel.devicespecificinfo) in the SYCL 2020 spec rev. 5.

Is there a way to access the information elsewhere from python (maybe in  `SyclKernel` or `numba_dpex.compiler.Kernel` attributes ?)

**Comment by oleksandr-pavlyk** [comment]
> > The `preferred_work_groups_size_multiple` is exposed in SYCL as a device-specific information about a kernel, see [Table 136](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#table.kernel.devicespecificinfo) in the SYCL 2020 spec rev. 5.
> 
> Is there a way to access the information elsewhere from python (maybe in `SyclKernel` or `numba_dpex.compiler.Kernel` attributes ?)

Not yet, but perhaps exposing it for `dpctl.SyclKernel` is the right thing to do. I will make it happen and tag you in the PR.

**Comment by fcharras** [comment]
Thank you very much.

> Querying it requires a kernel, which can only be extract from a kernel bundle in the executable state.

If I understand correctly, the information on the preferred work group size is only accessible once the kernel as been compiled (which makes sense because the compiler could have extra information on this value). Then if it is exposed with `dpctl.SyclKernel`, the correct order of instruction with `numba_dpex` would be:

- explicitly pass a signature to `numba_dpex.kernel` to trigger compilation immediately rather than delaying it to the first call (I don't know if this works yet but I think it's a common use case in numba, that's probably a good practice I've forgotten so far)
- query the `preferred_work_group_size_multiple` from the kernel it returns
- use this information to choose the `work_group_size` accordingly
- start the compute

**Comment by fcharras** [comment]
>  Could you please clarify what you mean by "local cache sizes"

You're right, that doesn't seem to exist in clinfo, sorry for the misdirection. The point only holds for `global_mem_cache_line_size` and `global_mem_cache_size` and `global_mem_cache_type` then. 

FYI, in https://github.com/soda-inria/sklearn-numba-dpex/pull/2 we've been using `global_mem_cache_size` to adjust the strategy ("privatization of updated arrays") used to avoid collisions on atomic updates in global memory, which is about creating some temporary writing structure that is larger but is hoped to be cached correctly.

**Comment by fcharras** [comment]
> Not yet, but perhaps exposing it for `dpctl.SyclKernel` is the right thing to do. I will make it happen and tag you in the PR.

Thank you, that would be awesome

**Comment by fcharras** [comment]
Thank you for the PR @oleksandr-pavlyk 

I've also come accross papers (e.g [this one](https://dl.acm.org/doi/abs/10.1145/3183713.3183735?casa_token=L-6PnNHYbo8AAAAA:EA6btsNIg7PH48bkSPFEUDIGkY5kY76qLZEVY367By0iI-LDWDcw4j7MP8-EOBP7_1JcNhKlF3nb) for top k) where the authors use some other information about the device for the finest grained optimizations, like bank size or size of simd units, it's also exposed in `pyopencl` although [it's a different API](https://documen.tician.de/pyopencl/tools.html#module-pyopencl.characterize) , but I don't think it's covered by the sycl spec at the moment.
