### ISSUE TITLE
`dpctl.tensor.from_numpy` forces C memory layout

### ISSUE THREAD

**Issue by fcharras** [IntelPython/dpctl#888]
The function `dpctl.tensor.from_numpy` does not expose an argument to choose the memory layout of the resulting tensor, like most other functions do in this namespace (see e.g. [`dpctl.tensor.empy`](https://intelpython.github.io/dpctl/latest/docfiles/dpctl/dpctl.tensor_functions_api.html#dpctl.tensor.empty).

But it does not inherit from the layout of the input numpy array either. What it does is forcing the C order.

Example:
```python
import dpnp
import dpctl
import dpctl.tensor
import numpy as np
arrayC = np.empty((3,4))
print(arrayC.strides)  # (32, 8) (in bytes) which is (4, 1) float64 items
tensorC = dpctl.tensor.from_numpy(arrayC)
print(tensorC.strides)  # (4, 1) items
arrayF = np.array(arrayC, order="F")
print(arrayF.strides)  # (8, 24) (in bytes) which is (1, 3) float64 items
tensorF = dpctl.tensor.from_numpy(arrayF)
print(tensorF.strides)  # expected (1, 3), but get (4, 1), meaning C-order
```

I would expect for `dpctl.tensor.from_numpy` to take an `order` argument, and as a default inherit from the input numpy array.

**Comment by oleksandr-pavlyk** [comment]
Please use `dpctl.tensor.asarray(np_array, order="F")`:

```python
tensorF1 = dpctl.tensor.asarray(arrayF, order="F")
print(tensorF1.strides)  # outputs (1, 3)
```

**Comment by fcharras** [comment]
Thank you, for me this solution works.
