### ISSUE TITLE
Numba with dpCtl can not find OpenCL interface via find_library('DPPLOpenCLInterface')

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#89]
See also https://github.com/IntelPython/numba/pull/7

**Comment by oleksandr-pavlyk** [comment]
Is this ticket still relevant ?

The location of the library is `os.path.dirname(dpctl.__file__)`:

```
In [5]: glob.glob(os.path.join(os.path.dirname(dpctl.__file__), '*.so'))
Out[5]:
['/localwork/repos/dpctl/dpctl/_sycl_core.cpython-37m-x86_64-linux-gnu.so',
 '/localwork/repos/dpctl/dpctl/libDPPLSyclInterface.so',
 '/localwork/repos/dpctl/dpctl/_memory.cpython-37m-x86_64-linux-gnu.so',
 '/localwork/repos/dpctl/dpctl/_opencl_core.abi3.so',
 '/localwork/repos/dpctl/dpctl/libDPPLOpenCLInterface.so']

```

**Comment by PokhodenkoSA** [comment]
It is relevant. Numba uses `ctypes.find_library('DPPLOpenCLInterface')`. It searches in LD_LIBRARY_PATH.
@oleksandr-pavlyk should Numba use your command `glob.glob(os.path.join(os.path.dirname(dpctl.__file__), '*.so'))`?
How to use it on Windows ?

**Comment by oleksandr-pavlyk** [comment]
There is no `LD_LIBRARY_PATH` on Windows, it would search `%PATH%`. I would search `glob.glob(os.path.join(os.path.dirname(dpctl.__file__), '*.dll'))`

**Comment by diptorupd** [comment]
`DPPLOpenCLInterface` will stop being used in Numba after we move the `DPPLSyclInterface`. So, even if this issue goes away we need to check for the `DPPLSyclInterface`.

**Comment by PokhodenkoSA** [comment]
@reazulhoque can you check how does Numba now searches for dpCtl libraries?

**Comment by PokhodenkoSA** [comment]
As I see now in this [lines](https://github.com/IntelPython/numba/blob/ec8862c8860185b203966a115942dd5b9b6380a2/numba/dppl/initialize.py#L19):
```python
    if platform == 'Windows':
        paths = glob.glob(os.path.join(os.path.dirname(dpctl.__file__), '*DPPLSyclInterface.dll'))
    else:
        paths = glob.glob(os.path.join(os.path.dirname(dpctl.__file__), '*DPPLSyclInterface*'))
```
Numba searches dpCtl libraries inside dpCtl package folder.
So this issue could be closed.
