### ISSUE TITLE
PyPI does not have the latest stable dpctl version

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#940]
PyPI has a 0.11.3 version of dpctl. The current stable version is 0.13 and development is going on towards the next stable 0.14 version. 

The PyPI version has to be updated so that users installing dpctl using pip get the latest stable version. Otherwise it is leading to bad user experience (see #808, #935).

**Comment by fcharras** [comment]
Maybe you could use github actions to set up an automated build & push to pypi when new tags are issued ? The runners available with github workflow look strong enough to run a building environment.

**Comment by oleksandr-pavlyk** [comment]
Closing as no longer pertinent.
