### ISSUE TITLE
dpctl doesn't support the cl::sycl::kernel in pybind11

### ISSUE THREAD

**Issue by chengjunlu** [IntelPython/dpctl#943]
I met issue when integrate the cl::sycl::kernel into python.

The error log like this:
```
TypeError: Unable to convert function return value to a Python type! The signature was
	(arg0: str, arg1: str, arg2: int, arg3: dpctl.SyclDevice) -> Tuple[int, cl::sycl::kernel, int, int]
```
It seems the sycl::device has been integrated successfully. But the cl::sycl::kernel is not supported.

Is there any plan to support the cl::sycl::kernel?

**Comment by chengjunlu** [comment]
@oleksandr-pavlyk 

Would you have any suggestion about the my issue?

**Comment by oleksandr-pavlyk** [comment]
For it to be added, we need to make Cython definitions of `dpctl.program.SyclProgram` and `dpctl.program.SyclKernel` public, add respective API and implement integration with pybind11. This definitely can be done.

Could you please share why this would be useful?

**Comment by chengjunlu** [comment]
I am working on integrating the Triton to SYCL for experimental. 

There is some sycl::kernel generated by Triton and pass to other python package to run. 

This feature would be great help in AI compiler component integration.

**Comment by oleksandr-pavlyk** [comment]
@chengjunlu Can you please look at #970 and see if it meets your needs?

**Comment by chengjunlu** [comment]
@oleksandr-pavlyk 
I quick reviewed the code changes. And looks good to me.

Do you want to me verify the branch before you merge it to main trunk?

**Comment by oleksandr-pavlyk** [comment]
> @oleksandr-pavlyk I quick reviewed the code changes. And looks good to me.
> 
> Do you want to me verify the branch before you merge it to main trunk?

Yes, that would be most helpful. Thank you

**Comment by chengjunlu** [comment]
> > @oleksandr-pavlyk I quick reviewed the code changes. And looks good to me.
> > Do you want to me verify the branch before you merge it to main trunk?
> 
> Yes, that would be most helpful. Thank you

I have tested it. And it works properly.
