### ISSUE TITLE
Function DPPLCString_Delete deletes char * which expected to be an array

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#95]
https://github.com/IntelPython/dpctl/blob/f8d0250b4a41724bc64346f2bbdaf9fdfc17e4a9/backends/source/dppl_utils.cpp#L30
Should it be `delete[] str;` ?

**Comment by diptorupd** [comment]
Of course. Thanks!

**Comment by diptorupd** [comment]
Pushed the fix in #93.
